packages:
  - apps/*
  - packages/*

allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  electron: true
  electron-winstaller: true
  esbuild: true
  prisma: true
  puppeteer: true
  sharp: true
  tesseract.js: true
