PRAGMA foreign_keys=OFF;

CREATE TABLE "new_Product" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "projectId" TEXT NOT NULL,
    "storeId" TEXT,
    "marketplace" TEXT NOT NULL,
    "marketplaceProductId" TEXT,
    "rank" INTEGER,
    "source" TEXT,
    "selectionReason" TEXT,
    "productType" TEXT,
    "title" TEXT NOT NULL,
    "priceMin" REAL,
    "priceMax" REAL,
    "priceAverage" REAL,
    "originalPrice" REAL,
    "discount" TEXT,
    "rating" REAL,
    "reviewCount" INTEGER,
    "monthlySold" INTEGER,
    "totalSold" INTEGER,
    "stock" BIGINT,
    "storeName" TEXT,
    "storeUrl" TEXT,
    "productUrl" TEXT NOT NULL,
    "mallStatus" BOOLEAN NOT NULL DEFAULT false,
    "officialStatus" BOOLEAN NOT NULL DEFAULT false,
    "starSeller" BOOLEAN NOT NULL DEFAULT false,
    "voucherText" TEXT,
    "shippingText" TEXT,
    "variantsJson" TEXT NOT NULL,
    "specificationsJson" TEXT NOT NULL,
    "description" TEXT,
    "rawJson" TEXT NOT NULL,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "Product_projectId_fkey" FOREIGN KEY ("projectId") REFERENCES "Project" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "Product_storeId_fkey" FOREIGN KEY ("storeId") REFERENCES "Store" ("id") ON DELETE SET NULL ON UPDATE CASCADE
);

INSERT INTO "new_Product" (
    "id",
    "projectId",
    "storeId",
    "marketplace",
    "marketplaceProductId",
    "rank",
    "source",
    "selectionReason",
    "productType",
    "title",
    "priceMin",
    "priceMax",
    "priceAverage",
    "originalPrice",
    "discount",
    "rating",
    "reviewCount",
    "monthlySold",
    "totalSold",
    "stock",
    "storeName",
    "storeUrl",
    "productUrl",
    "mallStatus",
    "officialStatus",
    "starSeller",
    "voucherText",
    "shippingText",
    "variantsJson",
    "specificationsJson",
    "description",
    "rawJson",
    "createdAt",
    "updatedAt"
)
SELECT
    "id",
    "projectId",
    "storeId",
    "marketplace",
    "marketplaceProductId",
    "rank",
    "source",
    "selectionReason",
    "productType",
    "title",
    "priceMin",
    "priceMax",
    "priceAverage",
    "originalPrice",
    "discount",
    "rating",
    "reviewCount",
    "monthlySold",
    "totalSold",
    "stock",
    "storeName",
    "storeUrl",
    "productUrl",
    "mallStatus",
    "officialStatus",
    "starSeller",
    "voucherText",
    "shippingText",
    "variantsJson",
    "specificationsJson",
    "description",
    "rawJson",
    "createdAt",
    "updatedAt"
FROM "Product";

DROP TABLE "Product";
ALTER TABLE "new_Product" RENAME TO "Product";

CREATE INDEX "Product_projectId_rank_idx" ON "Product"("projectId", "rank");
CREATE INDEX "Product_storeId_idx" ON "Product"("storeId");
CREATE INDEX "Product_marketplace_marketplaceProductId_idx" ON "Product"("marketplace", "marketplaceProductId");

PRAGMA foreign_key_check;
PRAGMA foreign_keys=ON;
