import { readFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import {
  BorderStyle,
  Document,
  ExternalHyperlink,
  HeadingLevel,
  ImageRun,
  Packer,
  Paragraph,
  Table,
  TableCell,
  TableRow,
  TextRun,
  WidthType,
  type ParagraphChild
} from "docx";
import sharp from "sharp";
import type { ReportData } from "../../application/services/ReportService.js";
import type { ReportGenerationPayload } from "../../shared/contracts.js";
import { DEFAULT_REPORT_SECTIONS, type ReportSectionConfig } from "../../shared/reportSections.js";

type DocxChild = Paragraph | Table;

const AUTHOR = "Wildan Ega Pradana";
const AUTHOR_LINKEDIN = "https://www.linkedin.com/in/wildanegapradana/";
const BLUE = "2563EB";
const INK = "111827";
const MUTED = "667085";
const BORDER = "D7DEE8";
const SOFT_BLUE = "EAF2FF";

export class ConsultingDocxReportExporter {
  async render(data: ReportData, payload?: ReportGenerationPayload): Promise<Buffer> {
    const sections = enabledSectionIds(payload?.sections ?? DEFAULT_REPORT_SECTIONS);
    const children: DocxChild[] = [
      titleParagraph("MarketPlace Keyword Competitor Analysis"),
      paragraph(data.project.keyword, { size: 36, bold: true, color: INK }),
      paragraph(`${data.project.marketplace} keyword competitor report generated from local guided evidence.`, { color: MUTED }),
      linkParagraph("Developer: Wildan Ega Pradana", AUTHOR_LINKEDIN),
      spacer()
    ];

    if (include(sections, "summaryMetrics", "cover")) {
      children.push(sectionHeading("Summary Metrics"), metricsTable(data), spacer());
    }
    if (include(sections, "keywordGeneral", "keywordRelevance", "topSales")) {
      children.push(...await keywordGeneralSection(data));
    }
    if (include(sections, "keyProducts", "keyProductTable")) {
      children.push(sectionHeading("Key Products"), keyProductTable(data), spacer());
    }
    if (include(
      sections,
      "productDetailFirstPage",
      "productDetailSlides",
      "productDetailDescription",
      "productDetailReviews",
      "productDetailUserMedia",
      "productDetailShopHomePage",
      "productDossiers",
      "reviewEvidence"
    )) {
      children.push(...await productDetailSections(data, sections));
    }
    if (include(sections, "keyStoreHomePage", "keyStoreProducts", "keyStoreBestSellers", "keyStoreVisualStyle", "storeOverview", "storeDossiers", "visualStyle")) {
      children.push(...await keyStoreSection(data, sections));
    }
    if (include(sections, "tiktokEvidence", "crossPlatformEvidence")) {
      children.push(...await tiktokSection(data));
    }

    const doc = new Document({
      title: data.project.keyword,
      subject: "Marketplace keyword competitor report",
      creator: AUTHOR,
      description: "Generated by MarketPlace Keyword Competitor Analysis",
      styles: {
        default: {
          document: {
            run: {
              font: "Arial",
              size: 21,
              color: INK
            },
            paragraph: {
              spacing: { after: 140, line: 270 }
            }
          }
        }
      },
      sections: [
        {
          properties: {
            page: {
              margin: { top: 720, right: 720, bottom: 720, left: 720 }
            }
          },
          children
        }
      ]
    });

    return Packer.toBuffer(doc);
  }
}

function enabledSectionIds(sections: ReportSectionConfig[]): Set<ReportSectionConfig["id"]> {
  return new Set(sections.filter((section) => section.enabled).map((section) => section.id));
}

function include(sections: Set<ReportSectionConfig["id"]>, ...ids: ReportSectionConfig["id"][]): boolean {
  return ids.some((id) => sections.has(id));
}

async function keywordGeneralSection(data: ReportData): Promise<DocxChild[]> {
  const children: DocxChild[] = [
    sectionHeading("Keyword General"),
    subHeading("Relevance"),
    ...await assetImageBlocks(data.assets.filter((asset) => asset.kind === "SEARCH_RESULT").slice(0, 2), "Relevance screenshot"),
    snapshotProductTable(data.products.filter((product) => product.source === "Relevance").slice(0, 40)),
    subHeading("Top Sales"),
    ...await assetImageBlocks(data.assets.filter((asset) => asset.kind === "TOP_SALES").slice(0, 2), "Top sales screenshot"),
    snapshotProductTable(data.products.filter((product) => product.source === "Top Sales").slice(0, 40)),
    spacer()
  ];
  return children;
}

async function productDetailSections(data: ReportData, sections: Set<ReportSectionConfig["id"]>): Promise<DocxChild[]> {
  const legacy = sections.has("productDossiers") || sections.has("reviewEvidence");
  const showFirstPage = legacy || sections.has("productDetailFirstPage");
  const showSlides = legacy || sections.has("productDetailSlides");
  const showDescription = legacy || sections.has("productDetailDescription");
  const showReviews = legacy || sections.has("productDetailReviews");
  const showUserMedia = legacy || sections.has("productDetailUserMedia");
  const showShopHome = legacy || sections.has("productDetailShopHomePage");
  const children: DocxChild[] = [sectionHeading("Product Detail")];
  for (const [index, product] of keyProductsForReport(data.products).entries()) {
    const raw = safeJson<{
      imageUrl?: string;
      images?: string[];
      videos?: string[];
      descriptionImages?: string[];
      reviewMediaImages?: string[];
      reviewMediaVideos?: string[];
      evidencePlan?: { productImages?: string[]; productVideos?: string[] };
      shopVouchers?: string[];
      bundleDeals?: string[];
    }>(product.rawJson, {});
    const assets = data.assets.filter((asset) => asset.ownerType === "PRODUCT" && asset.ownerId === product.id);
    const storeAssets = data.assets.filter((asset) => assetMatchesStore(asset, product.storeUrl));
    const productVideos = uniqueMediaUrls(raw.evidencePlan?.productVideos ?? [])
      .filter(isLikelyProductVideoUrl)
      .slice(0, 1);
    const productImages = uniqueMediaUrls([...(raw.evidencePlan?.productImages ?? []), ...(raw.images ?? []), raw.imageUrl])
      .filter(isReportProductImageUrl)
      .slice(0, productVideos.length > 0 ? 8 : 9);
    const reviewImages = uniqueMediaUrls(raw.reviewMediaImages ?? []).filter(isReportProductImageUrl).slice(0, 30);
    const reviewVideos = uniqueMediaUrls(raw.reviewMediaVideos ?? []).filter(isLikelyProductVideoUrl).slice(0, 12);
    children.push(subHeading(`Product ${index + 1}: ${product.title}`), productFactTable(product));
    if (showFirstPage) {
      children.push(tinyHeading("1st page"), ...await assetImageBlocks(assets.filter((asset) => asset.kind === "PRODUCT_PAGE"), "Product first page"));
    }
    if (showSlides) {
      children.push(tinyHeading("Slides"), ...await remoteImageBlocks(productImages, "Slide"));
      if (productVideos.length > 0) {
        children.push(bulletParagraph(`Product gallery video: ${productVideos[0]}`));
      }
    }
    if (showDescription) {
      children.push(tinyHeading("Description"), paragraph(product.description ?? "No browser-readable description captured.", { preserveLines: true }));
      children.push(...await remoteImageBlocks(uniqueMediaUrls(raw.descriptionImages ?? []).filter(isReportProductImageUrl).slice(0, 24), "Description image"));
      children.push(promotionTable(raw.shopVouchers ?? [], raw.bundleDeals ?? []));
    }
    if (showReviews) {
      children.push(tinyHeading("Reviews"), reviewTable(data.reviews.filter((review) => review.productId === product.id)));
    }
    if (showUserMedia) {
      children.push(tinyHeading("Media in user"), ...await remoteImageBlocks(reviewImages, "Review media"));
      if (reviewVideos.length > 0) {
        children.push(...reviewVideos.map((video, videoIndex) => bulletParagraph(`Review video ${videoIndex + 1}: ${video}`)));
      }
    }
    if (showShopHome) {
      children.push(tinyHeading("Shop Home Page"), ...await assetImageBlocks([
        ...assets.filter((asset) => asset.kind === "STORE_HOME"),
        ...storeAssets.filter((asset) => asset.kind === "STORE_HOME")
      ], "Shop home page"));
    }
    children.push(spacer());
  }
  return children;
}

async function keyStoreSection(data: ReportData, sections: Set<ReportSectionConfig["id"]>): Promise<DocxChild[]> {
  const legacy = sections.has("storeOverview") || sections.has("storeDossiers") || sections.has("visualStyle");
  const showHome = legacy || sections.has("keyStoreHomePage");
  const showProducts = legacy || sections.has("keyStoreProducts");
  const showBestSellers = legacy || sections.has("keyStoreBestSellers");
  const showVisualStyle = legacy || sections.has("keyStoreVisualStyle");
  const store = selectReportKeyStore(data);
  if (!store) {
    return [sectionHeading("Key Store"), paragraph("No Key Store evidence has been selected yet.", { color: MUTED })];
  }
  const assets = storeAssetsForReport(data, store);
  const children: DocxChild[] = [
    sectionHeading("Key Store"),
    subHeading(store.name),
    linkParagraph(store.url, store.url),
    tinyHeading("Overall"),
    paragraph(storeOverall(store, data), { preserveLines: true })
  ];
  if (showHome) {
    children.push(tinyHeading("Store Home Page"), ...await assetImageBlocks(assets.filter((asset) => asset.kind === "STORE_HOME"), "Store home page"));
  }
  if (showProducts) {
    children.push(tinyHeading("Products"), snapshotProductTable(data.products.filter((product) => product.source === "Store Products")));
  }
  if (showBestSellers) {
    children.push(tinyHeading("Best Sellers"), snapshotProductTable(data.products.filter((product) => product.source === "Store Best Sellers")));
  }
  if (showVisualStyle) {
    children.push(tinyHeading("Visual Style"), ...await assetImageBlocks(assets.filter((asset) => asset.kind === "STORE_BANNER"), "Store banner"));
  }
  return children;
}

async function tiktokSection(data: ReportData): Promise<DocxChild[]> {
  return [
    sectionHeading("TikTok Evidence"),
    ...await assetImageBlocks(data.assets.filter((asset) => asset.kind === "SOCIAL_ACCOUNT"), "TikTok evidence")
  ];
}

function metricsTable(data: ReportData): Table {
  return simpleTable([
    ["Products", String(data.products.length)],
    ["Stores", String(data.stores.length)],
    ["Reviews", String(data.reviews.length)],
    ["Evidence", String(data.assets.length)]
  ], [35, 65]);
}

function keyProductTable(data: ReportData): Table {
  const rows = keyProductsForReport(data.products).map((product, index) => [
    String(index + 1),
    productSourcePlacement(product),
    product.selectionReason ?? "-",
    product.title,
    productRawText(product, "productType") ?? product.productType ?? inferredProductType(product.title),
    productRawText(product, "monthlySoldText") ?? formatNumber(product.monthlySold),
    product.storeName ?? "-",
    storeType(product),
    formatCurrency(product.priceAverage),
    productRawText(product, "ratingText") ?? (product.rating ? product.rating.toFixed(1) : "-"),
    productRawText(product, "reviewText") ?? formatNumber(product.reviewCount),
    productRawText(product, "totalSoldText") ?? formatNumber(product.totalSold)
  ]);
  return tableWithHeader(
    ["No", "Source", "Reason", "Product Title", "Product Type", "Monthly Sold", "Store Name", "Store Type", "Price", "Rating", "Reviews", "Total Sold"],
    rows
  );
}

function snapshotProductTable(products: ReportData["products"]): Table {
  return tableWithHeader(
    ["Thumbnail", "Product name", "Price", "Rating", "Sold"],
    products.map((product) => [
      productImage(product) ?? "-",
      product.title,
      formatCurrency(product.priceAverage),
      productRawText(product, "ratingText") ?? (product.rating ? product.rating.toFixed(1) : "-"),
      productRawText(product, "monthlySoldText") ?? productRawText(product, "totalSoldText") ?? formatNumber(product.monthlySold ?? product.totalSold)
    ])
  );
}

function productFactTable(product: ReportData["products"][number]): Table {
  return simpleTable([
    ["Price", formatCurrency(product.priceAverage)],
    ["Store Name", product.storeName ?? "-"],
    ["Store Type", storeType(product)],
    ["Rating", productRawText(product, "ratingText") ?? (product.rating ? product.rating.toFixed(1) : "-")],
    ["Reviews", productRawText(product, "reviewText") ?? formatNumber(product.reviewCount)],
    ["Total Sold", productRawText(product, "totalSoldText") ?? formatNumber(product.totalSold)]
  ], [30, 70]);
}

function promotionTable(shopVouchers: string[], bundleDeals: string[]): Table {
  return simpleTable([
    ["Shop Vouchers", shopVouchers.slice(0, 8).join("\n") || "No promotion signal captured."],
    ["Bundle Deals", bundleDeals.slice(0, 8).join("\n") || "No promotion signal captured."]
  ], [30, 70]);
}

function reviewTable(reviews: ReportData["reviews"]): Table {
  const rows = curatedReviewsForReport(reviews).map((review) => [
    review.sentiment === "NEGATIVE" ? "Negative Reviews" : "Positive Reviews",
    review.rating ? `${review.rating} Star` : "-",
    formatReviewText(review)
  ]);
  return tableWithHeader(["Type", "Star Rated", "Comment - Include timestamp"], rows.length > 0 ? rows : [["-", "-", "No review text collected yet."]]);
}

async function remoteImageBlocks(urls: string[], label: string): Promise<DocxChild[]> {
  const blocks: DocxChild[] = [];
  const images = uniqueMediaUrls(urls).filter(isReportProductImageUrl).slice(0, 24);
  for (const [index, url] of images.entries()) {
    const image = await imageParagraph(url, `${label} ${index + 1}`);
    if (image) {
      blocks.push(image);
    }
  }
  if (blocks.length === 0) {
    blocks.push(paragraph(`No ${label.toLowerCase()} image captured.`, { color: MUTED }));
  }
  return blocks;
}

async function assetImageBlocks(assets: ReportData["assets"], label: string): Promise<DocxChild[]> {
  const blocks: DocxChild[] = [];
  for (const [index, asset] of assets.slice(0, 24).entries()) {
    const image = await imageParagraph(asset.path, asset.label || `${label} ${index + 1}`);
    if (image) {
      blocks.push(image);
    }
  }
  if (blocks.length === 0) {
    blocks.push(paragraph(`No ${label.toLowerCase()} evidence captured.`, { color: MUTED }));
  }
  return blocks;
}

async function imageParagraph(source: string, caption: string): Promise<Paragraph | undefined> {
  const image = await loadDocxImage(source);
  if (!image) {
    return undefined;
  }
  return new Paragraph({
    spacing: { before: 80, after: 120 },
    children: [
      new ImageRun({
        type: "jpg",
        data: image.buffer,
        transformation: { width: image.width, height: image.height },
        altText: {
          title: caption,
          name: caption,
          description: caption
        }
      }),
      new TextRun({ text: `\n${caption}`, color: MUTED, size: 17 })
    ]
  });
}

async function loadDocxImage(source: string): Promise<{ buffer: Buffer; width: number; height: number } | undefined> {
  try {
    const buffer = await readImageSource(source);
    const metadata = await sharp(buffer).metadata();
    const originalWidth = metadata.width ?? 900;
    const originalHeight = metadata.height ?? 650;
    const maxWidth = 520;
    const maxHeight = 360;
    const ratio = Math.min(maxWidth / originalWidth, maxHeight / originalHeight, 1);
    const width = Math.max(80, Math.round(originalWidth * ratio));
    const height = Math.max(80, Math.round(originalHeight * ratio));
    const output = await sharp(buffer)
      .rotate()
      .resize({ width, height, fit: "inside", withoutEnlargement: true })
      .jpeg({ quality: 88, mozjpeg: true })
      .toBuffer();
    return { buffer: output, width, height };
  } catch {
    return undefined;
  }
}

async function readImageSource(source: string): Promise<Buffer> {
  if (/^https?:\/\//iu.test(source)) {
    const controller = new AbortController();
    const timeout = setTimeout(() => controller.abort(), 9000);
    try {
      const response = await fetch(source, {
        signal: controller.signal,
        headers: {
          accept: "image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8",
          "user-agent": "Mozilla/5.0 MarketPlace Keyword Competitor Analysis"
        }
      });
      if (!response.ok) {
        throw new Error(`Image request failed with ${response.status}`);
      }
      return Buffer.from(await response.arrayBuffer());
    } finally {
      clearTimeout(timeout);
    }
  }
  const localPath = source.startsWith("file:") ? fileURLToPath(source) : source;
  return readFile(localPath);
}

function tableWithHeader(headers: string[], rows: string[][]): Table {
  return new Table({
    width: { size: 100, type: WidthType.PERCENTAGE },
    borders: tableBorders(),
    rows: [
      new TableRow({
        children: headers.map((header) => cell(header, { header: true }))
      }),
      ...rows.map((row) => new TableRow({ children: row.map((value) => cell(value)) }))
    ]
  });
}

function simpleTable(rows: string[][], columnWidths: [number, number]): Table {
  return new Table({
    width: { size: 100, type: WidthType.PERCENTAGE },
    columnWidths,
    borders: tableBorders(),
    rows: rows.map((row) => new TableRow({
      children: [
        cell(row[0] ?? "", { header: true, width: columnWidths[0] }),
        cell(row[1] ?? "", { width: columnWidths[1] })
      ]
    }))
  });
}

function cell(value: string, options: { header?: boolean; width?: number } = {}): TableCell {
  return new TableCell({
    width: options.width ? { size: options.width, type: WidthType.PERCENTAGE } : undefined,
    shading: options.header ? { fill: SOFT_BLUE, color: "auto" } : undefined,
    margins: { top: 100, bottom: 100, left: 100, right: 100 },
    children: [paragraph(value, { size: options.header ? 18 : 17, bold: options.header, preserveLines: true })]
  });
}

function tableBorders() {
  const border = { style: BorderStyle.SINGLE, color: BORDER, size: 1 };
  return {
    top: border,
    bottom: border,
    left: border,
    right: border,
    insideHorizontal: border,
    insideVertical: border
  };
}

function titleParagraph(text: string): Paragraph {
  return new Paragraph({
    heading: HeadingLevel.TITLE,
    spacing: { after: 180 },
    children: [new TextRun({ text, color: BLUE, size: 26, bold: true, allCaps: true })]
  });
}

function sectionHeading(text: string): Paragraph {
  return new Paragraph({
    heading: HeadingLevel.HEADING_1,
    spacing: { before: 260, after: 120 },
    children: [new TextRun({ text, color: INK, size: 30, bold: true })]
  });
}

function subHeading(text: string): Paragraph {
  return new Paragraph({
    heading: HeadingLevel.HEADING_2,
    spacing: { before: 180, after: 100 },
    children: [new TextRun({ text, color: INK, size: 24, bold: true })]
  });
}

function tinyHeading(text: string): Paragraph {
  return new Paragraph({
    heading: HeadingLevel.HEADING_3,
    spacing: { before: 120, after: 80 },
    children: [new TextRun({ text, color: BLUE, size: 20, bold: true })]
  });
}

function paragraph(text: string, options: { size?: number; bold?: boolean; color?: string; preserveLines?: boolean } = {}): Paragraph {
  const lines = options.preserveLines
    ? text.replace(/\r\n?/gu, "\n").split("\n")
    : [text.replace(/\s+/gu, " ").trim()];
  const children: ParagraphChild[] = lines.flatMap((line, index) => [
    new TextRun({
      text: line,
      break: index === 0 ? undefined : 1,
      size: options.size ?? 21,
      bold: options.bold,
      color: options.color ?? INK
    })
  ]);
  return new Paragraph({ children, spacing: { after: 100 } });
}

function bulletParagraph(text: string): Paragraph {
  return new Paragraph({
    bullet: { level: 0 },
    children: [new TextRun({ text, size: 19, color: INK })],
    spacing: { after: 80 }
  });
}

function linkParagraph(text: string, url: string): Paragraph {
  return new Paragraph({
    children: [
      new ExternalHyperlink({
        link: url,
        children: [
          new TextRun({
            text,
            color: BLUE,
            underline: {}
          })
        ]
      })
    ],
    spacing: { after: 100 }
  });
}

function spacer(): Paragraph {
  return new Paragraph({ children: [new TextRun({ text: "" })], spacing: { after: 120 } });
}

function keyProductsForReport(products: ReportData["products"]): ReportData["products"] {
  const merged = new Map<string, ReportData["products"][number]>();
  for (const product of products.filter((item) => item.source !== "Store Products" && item.source !== "Store Best Sellers")) {
    const key = productIdentity(product);
    const existing = merged.get(key);
    if (!existing) {
      merged.set(key, product);
      continue;
    }
    merged.set(key, mergeReportProductSignals(existing, product));
  }
  return [...merged.values()]
    .filter((product) => product.title && product.productUrl)
    .sort((left, right) => productQualityScore(right) - productQualityScore(left))
    .slice(0, 10);
}

function mergeReportProductSignals(left: ReportData["products"][number], right: ReportData["products"][number]): ReportData["products"][number] {
  const preferred = productQualityScore(right) > productQualityScore(left) ? right : left;
  const base = preferred === right ? left : right;
  const preferredRaw = safeJson<Record<string, unknown>>(preferred.rawJson, {});
  const baseRaw = safeJson<Record<string, unknown>>(base.rawJson, {});
  return {
    ...preferred,
    storeName: preferred.storeName ?? base.storeName,
    storeUrl: preferred.storeUrl ?? base.storeUrl,
    reviewCount: preferred.reviewCount ?? base.reviewCount,
    monthlySold: preferred.monthlySold ?? base.monthlySold,
    totalSold: preferred.totalSold ?? base.totalSold,
    rating: preferred.rating ?? base.rating,
    rawJson: JSON.stringify({
      ...baseRaw,
      ...preferredRaw,
      sourcePlacement: uniqueStrings([productSourcePlacement(preferred), productSourcePlacement(base)]).join(" / "),
      productType: preferredRaw.productType ?? baseRaw.productType,
      storeType: preferredRaw.storeType ?? baseRaw.storeType,
      monthlySoldText: preferredRaw.monthlySoldText ?? baseRaw.monthlySoldText,
      totalSoldText: preferredRaw.totalSoldText ?? baseRaw.totalSoldText,
      reviewText: preferredRaw.reviewText ?? baseRaw.reviewText,
      ratingText: preferredRaw.ratingText ?? baseRaw.ratingText
    })
  };
}

function productIdentity(product: ReportData["products"][number]): string {
  try {
    const url = new URL(product.productUrl);
    return url.pathname.replace(/\/$/u, "").toLowerCase();
  } catch {
    return product.title.toLowerCase().replace(/\s+/gu, " ").trim();
  }
}

function productQualityScore(product: ReportData["products"][number]): number {
  const source = product.source ?? "";
  const rank = product.rank ?? 99;
  const topSalesBoost = source === "Top Sales" ? 120 - Math.min(rank, 99) : 35 - Math.min(rank, 35);
  const monthlySoldScore = product.monthlySold ? Math.log10(product.monthlySold + 1) * 18 : 0;
  const totalSoldScore = product.totalSold ? Math.log10(product.totalSold + 1) * 12 : 0;
  const reviewScore = product.reviewCount ? Math.log10(product.reviewCount + 1) * 10 : 0;
  const ratingScore = product.rating ? product.rating * 12 : 0;
  const priceScore = product.priceAverage ? 8 : 0;
  const imageScore = productImage(product) ? 8 : 0;
  return topSalesBoost + monthlySoldScore + totalSoldScore + reviewScore + ratingScore + priceScore + imageScore;
}

function productImage(product: { rawJson: string }): string | undefined {
  const raw = safeJson<{ imageUrl?: string; images?: string[] }>(product.rawJson, {});
  return uniqueMediaUrls([raw.imageUrl, ...(raw.images ?? [])]).filter(isReportProductImageUrl)[0];
}

function productRawText(product: { rawJson?: string }, key: string): string | undefined {
  const raw = product.rawJson ? safeJson<Record<string, unknown>>(product.rawJson, {}) : {};
  const value = raw[key];
  return typeof value === "string" && value.trim() ? value.trim() : undefined;
}

function productSourcePlacement(product: ReportData["products"][number]): string {
  const rawPlacement = productRawText(product, "sourcePlacement");
  if (rawPlacement) {
    return formatSourcePlacement(rawPlacement, product.source);
  }
  const fallback = product.source && product.rank ? `${product.source} ${product.rank}` : product.source ?? "-";
  return formatSourcePlacement(fallback, product.source);
}

function formatSourcePlacement(value: string, source?: string | null): string {
  const parts = uniqueStrings(value.split("/").map((part) => part.trim()).filter(Boolean));
  if (parts.length === 0) {
    return "-";
  }
  return parts.map((part, index) => formatSourcePlacementToken(part, source, index)).join(" / ");
}

function formatSourcePlacementToken(value: string, source: string | null | undefined, index: number): string {
  if (/top\s+\d+\s+in\s+/iu.test(value)) {
    return value;
  }
  const rank = value.match(/\d+/u)?.[0] ?? "-";
  if (/relevance|relevancy|search/iu.test(value)) {
    return `Top ${rank} in relevance`;
  }
  if (/store\s*(popular|products)|popular|pop\b/iu.test(value)) {
    return `Top ${rank} in store popular`;
  }
  if (/store\s*(best|sales)|best\s*seller|top\s*sales|sales/iu.test(value)) {
    return `Top ${rank} in sales`;
  }
  const context = `${source ?? ""} ${value}`.toLowerCase();
  if (/store\s*(best|sales)|best\s*seller|top\s*sales|sales/iu.test(context)) {
    return `Top ${rank} in sales`;
  }
  if (/store\s*(popular|products)|popular|pop\b/iu.test(context)) {
    return `Top ${rank} in store popular`;
  }
  if (/relevance|relevancy|search/iu.test(context)) {
    return `Top ${rank} in relevance`;
  }
  if (index === 0 && source !== "Relevance") {
    return `Top ${rank} in sales`;
  }
  if (index === 1) {
    return `Top ${rank} in relevance`;
  }
  return value || "-";
}

function inferredProductType(title: string): string {
  const normalized = title.toLowerCase();
  if (/iphone\s*15|iphone15/u.test(normalized)) return "iphone15";
  if (/iphone/u.test(normalized)) return "iPhones";
  if (/bulu mata|eyelash|lashes|lash/u.test(normalized)) return "Eyelash";
  if (/eye\s*cream|krim mata|mata anti keriput/u.test(normalized)) return "eye cream";
  if (/lotion|body lotion|handbody/u.test(normalized)) return "body lotion";
  if (/lip\s*tint|lipstick|liptint/u.test(normalized)) return "lip tint";
  if (/serum/u.test(normalized)) return "serum";
  return "marketplace product";
}

function storeType(product: { mallStatus: boolean; officialStatus: boolean; starSeller: boolean; rawJson?: string }): string {
  const rawStoreType = product.rawJson ? productRawText(product, "storeType") : undefined;
  if (rawStoreType && /^(Mall ORI|Star\+|Star)$/u.test(rawStoreType)) {
    return rawStoreType;
  }
  if (product.officialStatus || product.mallStatus) {
    return "Mall ORI";
  }
  if (product.starSeller) {
    return "Star";
  }
  return "-";
}

function selectReportKeyStore(data: ReportData): ReportData["stores"][number] | undefined {
  const keyProducts = keyProductsForReport(data.products);
  const byStore = new Map<string, { count: number; gmv: number; storeName?: string; storeUrl?: string }>();
  for (const product of keyProducts) {
    const storeName = product.storeName ?? undefined;
    const storeUrl = product.storeUrl ?? undefined;
    const key = (storeUrl ?? storeName ?? "").toLowerCase();
    if (!key) {
      continue;
    }
    const current = byStore.get(key) ?? { count: 0, gmv: 0, storeName, storeUrl };
    current.count += 1;
    current.gmv += (product.priceAverage ?? 0) * (product.monthlySold ?? product.totalSold ?? 0);
    byStore.set(key, current);
  }
  const selected = [...byStore.values()].sort((left, right) => right.gmv - left.gmv || right.count - left.count)[0];
  if (!selected) {
    return data.stores[0];
  }
  return data.stores.find((store) =>
    (selected.storeUrl && sameReportUrl(store.url, selected.storeUrl)) ||
    (selected.storeName && store.name.toLowerCase() === selected.storeName.toLowerCase())
  ) ?? data.stores[0];
}

function storeAssetsForReport(data: ReportData, store: ReportData["stores"][number]): ReportData["assets"] {
  const storeOwned = data.assets.filter((asset) => asset.ownerType === "STORE" && asset.ownerId === store.id);
  if (storeOwned.length > 0) {
    return storeOwned;
  }
  return data.assets.filter((asset) => assetMatchesStore(asset, store.url));
}

function storeOverall(store: { rating?: number | null; followers?: number | null; voucherCount?: number | null }, data: ReportData): string {
  const analysis = data.analyses[0]?.resultJson ? safeJson<{ competitivePosition?: { observations?: string[] } } | null>(data.analyses[0].resultJson, null) : null;
  const observation = analysis?.competitivePosition?.observations?.[0];
  if (observation) {
    return observation;
  }
  const cues = [
    store.rating ? `rating ${store.rating}` : undefined,
    store.followers ? `${formatNumber(store.followers)} followers` : undefined,
    store.voucherCount ? `${formatNumber(store.voucherCount)} voucher signals` : undefined
  ].filter(Boolean);
  return cues.length > 0 ? `AI-ready store candidate with ${cues.join(", ")}.` : "AI-ready store candidate; screenshot evidence required for final scoring.";
}

function assetMatchesStore(asset: ReportData["assets"][number], storeUrl?: string | null): boolean {
  if (!storeUrl || !asset.sourceUrl) {
    return false;
  }
  const source = stripUrlNoise(asset.sourceUrl);
  const target = stripUrlNoise(storeUrl);
  return source.includes(target) || target.includes(source);
}

function sameReportUrl(left: string, right: string): boolean {
  return stripUrlNoise(left) === stripUrlNoise(right);
}

function stripUrlNoise(value: string): string {
  return value
    .toLowerCase()
    .replace(/^https?:\/\//u, "")
    .replace(/^www\./u, "")
    .replace(/[?#].*$/u, "")
    .replace(/\/$/u, "");
}

function curatedReviewsForReport(reviews: ReportData["reviews"]): ReportData["reviews"] {
  const readable = reviews.filter((review) => isReadableReviewText(review.comment));
  const positive = readable
    .filter((review) => review.sentiment === "POSITIVE" || (typeof review.rating === "number" && review.rating >= 5))
    .slice(0, 3);
  const negative = readable
    .filter((review) => review.sentiment === "NEGATIVE" || (typeof review.rating === "number" && review.rating <= 3))
    .slice(0, 2);
  return [...positive, ...negative].slice(0, 5);
}

function isReadableReviewText(value: string): boolean {
  const normalized = value.trim();
  return normalized.length >= 20 &&
    /\b20\d{2}[-/]\d{1,2}[-/]\d{1,2}(?:\s+\d{1,2}:\d{2})?\b/u.test(normalized) &&
    !/^https?:\/\//iu.test(normalized) &&
    !/(product ratings|all\s*\(|semua\s*\(|comments?\s*\(|with media|dengan media|repeat purchase|shop vouchers|bundle deals|barcode|bpom sesuai|dermatologically tested|add to cart|buy now)/iu.test(normalized);
}

function formatReviewText(review: ReportData["reviews"][number]): string {
  const commentLines = review.comment
    .replace(/\r\n?/gu, "\n")
    .split("\n")
    .map((line) => line.trim())
    .filter(Boolean);
  const hasDate = review.reviewDate ? review.comment.includes(review.reviewDate) : /\b20\d{2}[-/]\d{1,2}[-/]\d{1,2}/u.test(review.comment);
  const hasVariation = review.variation ? review.comment.toLowerCase().includes(review.variation.toLowerCase()) : false;
  const prefix = [
    hasDate ? undefined : review.reviewDate,
    review.variation && !hasVariation ? `variation : ${review.variation}` : undefined
  ].filter(Boolean);
  return [...prefix, ...commentLines].join("\n");
}

function isReportProductImageUrl(value: string): boolean {
  const normalized = value.trim();
  if (!normalized) {
    return false;
  }
  const lower = normalized.toLowerCase();
  if (/data:image\/svg|sprite|favicon|placeholder|default-avatar|avatar|profile|logo-shopee|shopee-logo|icon|arrow|chevron|next|previous|rating|star|cart|chat|help|verify/iu.test(lower)) {
    return false;
  }
  if (/\/(?:icons?|sprites?|avatars?)\//iu.test(lower)) {
    return false;
  }
  return /^(https?:|file:|data:image\/(?:png|jpe?g|webp|avif|gif|bmp))/iu.test(normalized);
}

function isLikelyProductVideoUrl(value: string): boolean {
  const lower = value.toLowerCase();
  return /^(https?:|file:)/iu.test(value) &&
    /\.(?:mp4|webm|m3u8)(?:$|[?#])/iu.test(lower) &&
    !/(rating|review|comment|buyer|user-media|media-in-user)/iu.test(lower);
}

function uniqueMediaUrls(values: Array<string | undefined>): string[] {
  const seen = new Set<string>();
  const unique: string[] = [];
  for (const value of values) {
    const normalized = value?.trim();
    if (!normalized) {
      continue;
    }
    const key = normalized
      .replace(/([?&](?:x-oss-process|width|height|resize|quality|format)=[^&]+)/giu, "")
      .replace(/@resize_[^?]+/giu, "")
      .replace(/@!.*$/u, "")
      .toLowerCase();
    if (seen.has(key)) {
      continue;
    }
    seen.add(key);
    unique.push(normalized);
  }
  return unique;
}

function uniqueStrings(values: Array<string | undefined>): string[] {
  const seen = new Set<string>();
  const unique: string[] = [];
  for (const value of values) {
    if (!value || seen.has(value)) {
      continue;
    }
    seen.add(value);
    unique.push(value);
  }
  return unique;
}

function safeJson<T>(value: string, fallback: T): T {
  try {
    return JSON.parse(value) as T;
  } catch {
    return fallback;
  }
}

function formatCurrency(value?: number | null): string {
  if (!value) {
    return "-";
  }
  return new Intl.NumberFormat("id-ID", {
    style: "currency",
    currency: "IDR",
    maximumFractionDigits: 0
  }).format(value);
}

function formatNumber(value?: number | null): string {
  if (value === null || value === undefined) {
    return "-";
  }
  return new Intl.NumberFormat("id-ID", { maximumFractionDigits: 0 }).format(value);
}
