export type ReportLanguage = "id-ID" | "en-US" | "zh-CN";

const REPORT_TRANSLATIONS: Record<Exclude<ReportLanguage, "en-US">, Record<string, string>> = {
  "id-ID": {
    "Marketplace Intelligence Report": "Laporan Intelijen Marketplace",
    "Marketplace Research Report": "Laporan Riset Marketplace",
    "keyword competitor report generated from local guided evidence.": "laporan kompetitor kata kunci yang dibuat dari bukti lokal terpandu.",
    "Summary Metrics": "Ringkasan Metrik",
    "Keyword General": "Ringkasan Kata Kunci",
    "Key Products": "Produk Utama",
    "Product Detail": "Detail Produk",
    "Key Store Page List": "Daftar Halaman Toko Utama",
    "Intelligence and Recommendations": "Intelijen dan Rekomendasi",
    "Specialist Assessment": "Penilaian Spesialis",
    "Evidence-Based Market Recommendations": "Rekomendasi Pasar Berbasis Bukti",
    "Keyword Search Analysis & Top 10 Competition Matrix": "Analisis Pencarian Kata Kunci & Matriks 10 Kompetitor Teratas",
    "Keyword Search Analysis &amp; Top 10 Competition Matrix": "Analisis Pencarian Kata Kunci & Matriks 10 Kompetitor Teratas",
    "Synthesized Category Insights": "Sintesis Insight Kategori",
    "Product Name": "Nama Produk",
    "USP/Key Claim": "USP/Klaim Utama",
    "Short Description": "Deskripsi Singkat",
    "PRICING ARCHITECTURE & TIERING": "ARSITEKTUR & TINGKAT HARGA",
    "PRICING ARCHITECTURE &amp; TIERING": "ARSITEKTUR & TINGKAT HARGA",
    "COMPETITIVE POSITIONING & KEY CLAIMS": "POSISI KOMPETITIF & KLAIM UTAMA",
    "COMPETITIVE POSITIONING &amp; KEY CLAIMS": "POSISI KOMPETITIF & KLAIM UTAMA",
    "CUSTOMER TRUST & RATING SIGNALS": "KEPERCAYAAN PELANGGAN & SINYAL PENILAIAN",
    "CUSTOMER TRUST &amp; RATING SIGNALS": "KEPERCAYAAN PELANGGAN & SINYAL PENILAIAN",
    "DEMAND CONCENTRATION & PRODUCT MOMENTUM": "KONSENTRASI PERMINTAAN & MOMENTUM PRODUK",
    "DEMAND CONCENTRATION &amp; PRODUCT MOMENTUM": "KONSENTRASI PERMINTAAN & MOMENTUM PRODUK",
    "CATEGORY OPPORTUNITIES & RECOMMENDED ACTIONS": "PELUANG KATEGORI & TINDAKAN YANG DIREKOMENDASIKAN",
    "CATEGORY OPPORTUNITIES &amp; RECOMMENDED ACTIONS": "PELUANG KATEGORI & TINDAKAN YANG DIREKOMENDASIKAN",
    "Executive Summary": "Ringkasan Eksekutif",
    "Strengths": "Kekuatan",
    "Weaknesses": "Kelemahan",
    "Opportunities": "Peluang",
    "Threats": "Ancaman",
    "Market Intelligence": "Intelijen Pasar",
    "Recommendations": "Rekomendasi",
    "Priority": "Prioritas",
    "Action": "Tindakan",
    "Rationale": "Alasan",
    "Limitations": "Keterbatasan",
    "None reported": "Tidak ada yang dilaporkan",
    "Pricing Analysis": "Analisis Harga",
    "Store Analysis": "Analisis Toko",
    "Competitor Analysis": "Analisis Kompetitor",
    "Visual Analysis": "Analisis Visual",
    "No analysis generated.": "Analisis belum dibuat.",
    "No executive summary was generated.": "Ringkasan eksekutif belum dibuat.",
    "No structured intelligence analysis has been generated yet.": "Analisis intelijen terstruktur belum dibuat.",
    "TikTok Evidence": "Bukti TikTok",
    "Cross-Platform Evidence": "Bukti Lintas Platform",
    "Store Home Page": "Halaman Utama Toko",
    "Store Data": "Data Toko",
    "Store Product Categories": "Kategori Produk Toko",
    "Popular Products": "Produk Populer",
    "Best Sellers": "Produk Terlaris",
    "Visual Shop Banner": "Banner Visual Toko",
    "Products": "Produk",
    "Stores": "Toko",
    "Reviews": "Ulasan",
    "Assets": "Bukti",
    "Source": "Sumber",
    "Reason": "Alasan",
    "Product Title": "Judul Produk",
    "Product Type": "Jenis Produk",
    "Monthly Sold": "Terjual Bulanan",
    "Store Name": "Nama Toko",
    "Store Type": "Jenis Toko",
    "Price": "Harga",
    "Rating": "Peringkat",
    "Total Sold": "Total Terjual",
    "Description Store": "Deskripsi Toko",
    "Chat Performance": "Performa Chat",
    "Joined": "Bergabung",
    "Followers": "Pengikut",
    "Following": "Mengikuti",
    "Category Name": "Nama Kategori",
    "Total Product": "Total Produk",
    "Overall": "Ringkasan"
  },
  "zh-CN": {
    "Marketplace Intelligence Report": "市场情报报告",
    "Marketplace Research Report": "市场研究报告",
    "keyword competitor report generated from local guided evidence.": "基于本地引导证据生成的关键词竞争报告。",
    "Summary Metrics": "指标摘要",
    "Keyword General": "关键词概览",
    "Key Products": "重点产品",
    "Product Detail": "产品详情",
    "Key Store Page List": "重点店铺页面",
    "Intelligence and Recommendations": "洞察与建议",
    "Specialist Assessment": "专家评估",
    "Evidence-Based Market Recommendations": "基于证据的市场建议",
    "Keyword Search Analysis & Top 10 Competition Matrix": "关键词搜索分析与十大竞品矩阵",
    "Keyword Search Analysis &amp; Top 10 Competition Matrix": "关键词搜索分析与十大竞品矩阵",
    "Synthesized Category Insights": "综合品类洞察",
    "Product Name": "产品名称",
    "USP/Key Claim": "独特卖点/核心主张",
    "Short Description": "简短描述",
    "PRICING ARCHITECTURE & TIERING": "价格架构与分层",
    "PRICING ARCHITECTURE &amp; TIERING": "价格架构与分层",
    "COMPETITIVE POSITIONING & KEY CLAIMS": "竞争定位与核心主张",
    "COMPETITIVE POSITIONING &amp; KEY CLAIMS": "竞争定位与核心主张",
    "CUSTOMER TRUST & RATING SIGNALS": "客户信任与评分信号",
    "CUSTOMER TRUST &amp; RATING SIGNALS": "客户信任与评分信号",
    "DEMAND CONCENTRATION & PRODUCT MOMENTUM": "需求集中度与产品动能",
    "DEMAND CONCENTRATION &amp; PRODUCT MOMENTUM": "需求集中度与产品动能",
    "CATEGORY OPPORTUNITIES & RECOMMENDED ACTIONS": "品类机会与建议行动",
    "CATEGORY OPPORTUNITIES &amp; RECOMMENDED ACTIONS": "品类机会与建议行动",
    "Executive Summary": "执行摘要",
    "Strengths": "优势",
    "Weaknesses": "劣势",
    "Opportunities": "机会",
    "Threats": "威胁",
    "Market Intelligence": "市场洞察",
    "Recommendations": "建议",
    "Priority": "优先级",
    "Action": "行动",
    "Rationale": "依据",
    "Limitations": "局限性",
    "None reported": "无报告事项",
    "Pricing Analysis": "定价分析",
    "Store Analysis": "店铺分析",
    "Competitor Analysis": "竞品分析",
    "Visual Analysis": "视觉分析",
    "No analysis generated.": "尚未生成分析。",
    "No executive summary was generated.": "尚未生成执行摘要。",
    "No structured intelligence analysis has been generated yet.": "尚未生成结构化市场洞察。",
    "TikTok Evidence": "TikTok 证据",
    "Cross-Platform Evidence": "跨平台证据",
    "Store Home Page": "店铺首页",
    "Store Data": "店铺数据",
    "Store Product Categories": "店铺产品类别",
    "Popular Products": "热门产品",
    "Best Sellers": "畅销产品",
    "Visual Shop Banner": "店铺横幅",
    "Products": "产品",
    "Stores": "店铺",
    "Reviews": "评论",
    "Assets": "证据",
    "Source": "来源",
    "Reason": "原因",
    "Product Title": "产品标题",
    "Product Type": "产品类型",
    "Monthly Sold": "月销量",
    "Store Name": "店铺名称",
    "Store Type": "店铺类型",
    "Price": "价格",
    "Rating": "评分",
    "Total Sold": "总销量",
    "Description Store": "店铺描述",
    "Chat Performance": "聊天表现",
    "Joined": "入驻时间",
    "Followers": "粉丝",
    "Following": "关注",
    "Category Name": "类别名称",
    "Total Product": "产品总数",
    "Overall": "总体摘要"
  }
};

export function normalizeReportLanguage(value: unknown): ReportLanguage {
  return value === "id-ID" || value === "zh-CN" ? value : "en-US";
}

export function reportText(language: ReportLanguage, source: string): string {
  return language === "en-US" ? source : REPORT_TRANSLATIONS[language][source] ?? source;
}

export function localizeReportHtml(html: string, language: ReportLanguage): string {
  if (language === "en-US") {
    return html;
  }
  return Object.entries(REPORT_TRANSLATIONS[language]).reduce((localized, [source, translation]) => {
    const exactNode = localized.split(">" + source + "<").join(">" + translation + "<");
    const numberedHeadings = [1, 2, 3, 4, 5].reduce(
      (value, index) => value.split(`>${index}. ${source}<`).join(`>${index}. ${translation}<`),
      exactNode
    );
    const labelPrefix = numberedHeadings.split(">" + source + ":").join(">" + translation + ":");
    if (source === "keyword competitor report generated from local guided evidence.") {
      return labelPrefix.split(source).join(translation);
    }
    return labelPrefix;
  }, html);
}
