export type AppLanguage = "id-ID" | "en-US" | "zh-CN";

export type AppLanguageOption = {
  id: AppLanguage;
  label: string;
  nativeLabel: string;
  shortLabel: string;
  preview: string;
};

export const APP_LANGUAGES: AppLanguageOption[] = [
  {
    id: "en-US",
    label: "English",
    nativeLabel: "English",
    shortLabel: "EN",
    preview: "Research workspace"
  },
  {
    id: "id-ID",
    label: "Indonesian",
    nativeLabel: "Bahasa Indonesia",
    shortLabel: "ID",
    preview: "Ruang kerja riset"
  },
  {
    id: "zh-CN",
    label: "Chinese",
    nativeLabel: "简体中文",
    shortLabel: "中文",
    preview: "市场研究工作区"
  }
];

const TRANSLATIONS: Record<Exclude<AppLanguage, "en-US">, Record<string, string>> = {
  "id-ID": {
    "Research Workspace": "Ruang Kerja Riset",
    "Keyword Projects": "Proyek Kata Kunci",
    Reports: "Laporan",
    Settings: "Pengaturan",
    Research: "Riset",
    Library: "Pustaka",
    System: "Sistem",
    "New Research": "Riset Baru",
    "Local Evidence Vault": "Brankas Bukti Lokal",
    "Open Settings": "Buka Pengaturan",
    "Marketplace Intelligence OS": "Marketplace Intelligence OS",
    "Research Product Market": "Research Product Market",
    "Clear search": "Hapus pencarian",
    Home: "Beranda",
    Language: "Bahasa",
    "Switch theme": "Ganti tema",
    "Light theme": "Tema terang",
    "Dark theme": "Tema gelap",
    "Create Analysis": "Buat Analisis",
    "Open setup": "Buka pengaturan riset",
    "Start a guided marketplace evidence session. You control the browser, the app captures each required report step.": "Mulai sesi bukti marketplace terpandu. Anda mengendalikan browser, dan aplikasi merekam setiap langkah laporan yang diperlukan.",
    "Desired Keyword": "Kata Kunci",
    "Product Category": "Kategori Produk",
    "Date Created": "Tanggal Dibuat",
    "Collection Platform": "Platform Koleksi",
    "Shop Type": "Jenis Toko",
    "Price Range (IDR)": "Rentang Harga (IDR)",
    "Coming soon": "Segera hadir",
    Minimum: "Minimum",
    Maximum: "Maksimum",
    to: "hingga",
    "Maximum price must be greater than or equal to minimum price.": "Harga maksimum harus lebih besar atau sama dengan harga minimum.",
    "Start Collection": "Mulai Koleksi",
    "Back": "Kembali",
    "Report Generator": "Generator Laporan",
    "Generate reports from saved marketplace evidence.": "Buat laporan dari bukti marketplace yang tersimpan.",
    "Report language": "Bahasa laporan",
    "Report structure": "Struktur laporan",
    "Drag sections to reorder the generated document.": "Seret bagian untuk mengubah urutan dokumen yang dibuat.",
    "DOCX preview": "Pratinjau DOCX",
    "Evidence-grounded specialist recommendations": "Rekomendasi spesialis berbasis bukti",
    "Configure OpenAI or Gemini to enable specialist intelligence recommendations.": "Konfigurasikan OpenAI atau Gemini untuk mengaktifkan rekomendasi intelijen spesialis.",
    "No report sections selected.": "Belum ada bagian laporan yang dipilih.",
    "Single Report": "Laporan Tunggal",
    "Bulk Report": "Laporan Massal",
    Project: "Proyek",
    Projects: "Proyek",
    "File types": "Jenis file",
    "Where to save": "Lokasi penyimpanan",
    "Choose folder": "Pilih folder",
    "Choose Report Content": "Pilih Isi Laporan",
    Edit: "Edit",
    Save: "Simpan",
    Cancel: "Batal",
    Generate: "Buat",
    "Generate Report": "Buat Laporan",
    "Generate Bulk Reports": "Buat Laporan Massal",
    "Generated Reports": "Laporan Tersimpan",
    Preview: "Pratinjau",
    Locate: "Tampilkan lokasi",
    Open: "Buka",
    Delete: "Hapus",
    "No generated reports yet.": "Belum ada laporan yang dibuat.",
    "Report content settings": "Pengaturan isi laporan",
    "Use saved content settings": "Gunakan pengaturan isi tersimpan",
    "Select projects": "Pilih proyek",
    "Select all": "Pilih semua",
    "Clear all": "Hapus pilihan",
    "Save content settings": "Simpan pengaturan isi",
    "Content settings saved": "Pengaturan isi tersimpan",
    "All categories": "Semua kategori",
    "Inspect saved marketplace research or continue an active collection.": "Periksa riset marketplace tersimpan atau lanjutkan koleksi aktif.",
    Inspect: "Periksa",
    "Continue Collection": "Lanjutkan Koleksi",
    "Collect Again": "Koleksi Ulang",
    "Back to Projects": "Kembali ke Proyek",
    "Select a project": "Pilih proyek",
    "No project": "Tidak ada proyek",
    "Filename template": "Templat nama file",
    "Filename preview": "Pratinjau nama file",
    "sections enabled": "bagian aktif",
    "Generating Report": "Membuat Laporan",
    "Rendering report and export files": "Merender laporan dan file ekspor",
    "Report generation complete": "Pembuatan laporan selesai",
    "This report is still being prepared. Final export actions will become available when generation completes.": "Laporan ini masih diproses. Aksi ekspor akhir akan tersedia setelah proses selesai.",
    "Search projects": "Cari proyek",
    Uncategorized: "Tanpa kategori",
    "No matching projects.": "Tidak ada proyek yang cocok.",
    "Bulk report history": "Riwayat laporan massal",
    "No bulk reports generated yet.": "Belum ada laporan massal yang dibuat.",
    "Bulk report ready": "Laporan massal siap",
    "Configure the evidence sections used by single and bulk reports.": "Atur bagian bukti yang digunakan oleh laporan tunggal dan massal.",
    "Back to projects": "Kembali ke proyek",
    "Saved Collection Progress": "Progres Koleksi Tersimpan",
    "Saved URL": "URL Tersimpan",
    "No browser URL saved": "Tidak ada URL browser tersimpan",
    "Current Step": "Langkah Saat Ini",
    "View Mode": "Mode Tampilan",
    "Not selected": "Belum dipilih",
    Default: "Standar",
    Media: "Media",
    Products: "Produk",
    Stores: "Toko",
    Reviews: "Ulasan",
    "Price Range": "Rentang Harga",
    "products with price evidence": "produk dengan bukti harga",
    "collected marketplace stores": "toko marketplace yang dikoleksi",
    "Synthesized marketplace competition evidence": "Sintesis bukti persaingan marketplace",
    "Generated with": "Dihasilkan dengan",
    "Generate this section from the saved project evidence and configured AI provider.": "Buat bagian ini dari bukti proyek tersimpan dan penyedia AI yang telah dikonfigurasi.",
    Regenerate: "Buat Ulang",
    "Configure an OpenAI or Gemini API key in Settings before generating this AI-only section.": "Konfigurasikan kunci API OpenAI atau Gemini di Pengaturan sebelum membuat bagian khusus AI ini.",
    "Product Name": "Nama Produk",
    "USP / Key Claim": "USP / Klaim Utama",
    "Short Description": "Deskripsi Singkat",
    "Synthesized Category Insights": "Sintesis Insight Kategori",
    "AI competition analysis is ready to generate": "Analisis persaingan AI siap dibuat",
    "The generated matrix and five specialist insights will also be used by report exports.": "Matriks dan lima insight spesialis yang dibuat juga akan digunakan dalam ekspor laporan.",
    "Analysis Session": "Sesi Analisis",
    "Expand analysis session": "Perluas sesi analisis",
    "Collapse analysis session": "Ciutkan sesi analisis",
    Keyword: "Kata Kunci",
    Category: "Kategori",
    Platform: "Platform",
    Created: "Dibuat",
    "Collection Progress": "Progres Koleksi",
    "Key Product List": "Daftar Produk Utama",
    "Store Page List": "Daftar Halaman Toko",
    "Part 1": "Bagian 1",
    "Part 2": "Bagian 2",
    "Part 3": "Bagian 3",
    "Part 1 - Keyword General": "Bagian 1 - Kata Kunci Umum",
    "Part 2 - Product Details": "Bagian 2 - Detail Produk",
    "Part 3 - Key Store Pages": "Bagian 3 - Halaman Toko Utama",
    "steps in this part": "langkah di bagian ini",
    total: "total",
    Overview: "Ringkasan",
    "AI evidence analysis": "Analisis bukti AI",
    "Evidence-based overview": "Ringkasan berbasis bukti",
    "Analyzing current evidence…": "Menganalisis bukti saat ini…",
    "Key Store Page List": "Daftar Halaman Toko Utama",
    "store pages": "halaman toko",
    "Each store keeps its own homepage, profile, ratings, categories, products, banner, and TikTok evidence.": "Setiap toko menyimpan beranda, profil, penilaian, kategori, produk, banner, dan bukti TikTok secara terpisah.",
    "Continue Store Collection": "Lanjutkan Koleksi Toko",
    "No store pages yet. Approve qualified products or add a store page first.": "Belum ada halaman toko. Setujui produk yang memenuhi syarat atau tambahkan halaman toko terlebih dahulu.",
    Followers: "Pengikut",
    Following: "Mengikuti",
    Rating: "Penilaian",
    "Chat Performance": "Performa Chat",
    Joined: "Bergabung",
    "Description Store": "Deskripsi Toko",
    "No store rating samples collected. Desktop view is recommended for this collector.": "Belum ada sampel penilaian toko yang dikoleksi. Tampilan desktop disarankan untuk kolektor ini.",
    "Desktop view is recommended for collecting store ratings.": "Tampilan desktop disarankan untuk mengoleksi penilaian toko.",
    "Open rated product": "Buka produk yang dinilai",
    "Product link unavailable": "Tautan produk tidak tersedia",
    "Attached media": "Media terlampir",
    Product: "Produk",
    Comment: "Komentar",
    "Seller response": "Respons penjual",
    No: "No",
    "Category Name": "Nama Kategori",
    "Total Product": "Total Produk",
    "Loading settings.": "Memuat pengaturan.",
    General: "Umum",
    "AI Configuration": "Konfigurasi AI",
    Theme: "Tema",
    Dark: "Gelap",
    Light: "Terang",
    "Preferred Browser": "Browser Pilihan",
    "not detected": "tidak terdeteksi",
    "Export folder": "Folder ekspor",
    "Choose report export folder": "Pilih folder ekspor laporan",
    "Reset report export folder to default": "Kembalikan folder ekspor laporan ke standar",
    "Screenshot folder": "Folder tangkapan layar",
    "Choose screenshot folder": "Pilih folder tangkapan layar",
    "Reset screenshot folder to default": "Kembalikan folder tangkapan layar ke standar",
    Concurrency: "Proses Bersamaan",
    "Report filename template": "Templat nama file laporan",
    "Save Settings": "Simpan Pengaturan",
    Runtime: "Runtime",
    "Marketplace adapters": "Adaptor marketplace",
    "Local database": "Database lokal",
    Application: "Aplikasi",
    Version: "Versi",
    Packaged: "Dikemas",
    "Yes value": "Ya",
    "No value": "Tidak",
    folders: "folder",
    Data: "Data",
    "Browser profiles": "Profil browser",
    "Open App Folder": "Buka Folder Aplikasi",
    "OpenAI API key": "Kunci API OpenAI",
    "Gemini API key": "Kunci API Gemini",
    "Save AI Configuration": "Simpan Konfigurasi AI",
    "AI API Key Setup": "Pengaturan Kunci API AI",
    "API keys are secrets. Keep each key private, do not place it in screenshots or source control, and rotate it immediately if it is exposed.": "Kunci API bersifat rahasia. Jaga setiap kunci tetap privat, jangan tampilkan dalam tangkapan layar atau kontrol sumber, dan segera ganti jika terekspos.",
    "Official provider setup": "Pengaturan penyedia resmi",
    Configured: "Terkonfigurasi",
    "Not configured": "Belum dikonfigurasi",
    "Official guide": "Panduan resmi",
    "Open OpenAI API Keys": "Buka Kunci API OpenAI",
    "Open Gemini API Keys": "Buka Kunci API Gemini",
    "Open the OpenAI API Keys page and sign in.": "Buka halaman Kunci API OpenAI lalu masuk.",
    "Select Create new secret key and copy it when it is shown.": "Pilih Buat kunci rahasia baru lalu salin saat ditampilkan.",
    "Paste it into OpenAI API key above, then save settings.": "Tempel ke kolom kunci API OpenAI di atas, lalu simpan pengaturan.",
    "Open the Gemini API Keys page and sign in with your Google account.": "Buka halaman Kunci API Gemini lalu masuk dengan akun Google Anda.",
    "Select Create API key, choose a project, and copy the generated key.": "Pilih Buat kunci API, pilih proyek, lalu salin kunci yang dibuat.",
    "Paste it into Gemini API key above, then save settings.": "Tempel ke kolom kunci API Gemini di atas, lalu simpan pengaturan.",
    "Expand sidebar": "Perluas sidebar",
    "Collapse sidebar": "Ciutkan sidebar",
    "Primary navigation": "Navigasi utama",
    Available: "Tersedia",
    "Keyword projects, screenshots, reports, browser sessions, and keys stay on this machine.": "Proyek kata kunci, tangkapan layar, laporan, sesi browser, dan kunci tetap tersimpan di perangkat ini.",
    "Developer profile": "Profil pengembang",
    Developer: "Pengembang",
    "Open developer profile": "Buka profil pengembang",
    Completed: "Selesai",
    Incomplete: "Belum selesai"
  },
  "zh-CN": {
    "Research Workspace": "市场研究工作区",
    "Keyword Projects": "关键词项目",
    Reports: "报告",
    Settings: "设置",
    Research: "研究",
    Library: "资料库",
    System: "系统",
    "New Research": "新建研究",
    "Local Evidence Vault": "本地证据库",
    "Open Settings": "打开设置",
    "Marketplace Intelligence OS": "Marketplace Intelligence OS",
    "Research Product Market": "产品市场研究",
    "Clear search": "清除搜索",
    Home: "首页",
    Language: "语言",
    "Switch theme": "切换主题",
    "Light theme": "浅色主题",
    "Dark theme": "深色主题",
    "Create Analysis": "创建分析",
    "Open setup": "打开研究设置",
    "Start a guided marketplace evidence session. You control the browser, the app captures each required report step.": "开始引导式市场证据会话。您控制浏览器，应用会记录报告所需的每个步骤。",
    "Desired Keyword": "目标关键词",
    "Product Category": "产品类别",
    "Date Created": "创建日期",
    "Collection Platform": "采集平台",
    "Shop Type": "店铺类型",
    "Price Range (IDR)": "价格范围（IDR）",
    "Coming soon": "即将推出",
    Minimum: "最低",
    Maximum: "最高",
    to: "至",
    "Maximum price must be greater than or equal to minimum price.": "最高价格必须大于或等于最低价格。",
    "Start Collection": "开始采集",
    "Back": "返回",
    "Report Generator": "报告生成器",
    "Generate reports from saved marketplace evidence.": "从已保存的市场证据生成报告。",
    "Report language": "报告语言",
    "Report structure": "报告结构",
    "Drag sections to reorder the generated document.": "拖动章节以调整生成文档的顺序。",
    "DOCX preview": "DOCX 预览",
    "Evidence-grounded specialist recommendations": "基于证据的专业建议",
    "Configure OpenAI or Gemini to enable specialist intelligence recommendations.": "配置 OpenAI 或 Gemini 以启用专业市场情报建议。",
    "No report sections selected.": "尚未选择报告章节。",
    "Single Report": "单个报告",
    "Bulk Report": "批量报告",
    Project: "项目",
    Projects: "项目",
    "File types": "文件类型",
    "Where to save": "保存位置",
    "Choose folder": "选择文件夹",
    "Choose Report Content": "选择报告内容",
    Edit: "编辑",
    Save: "保存",
    Cancel: "取消",
    Generate: "生成",
    "Generate Report": "生成报告",
    "Generate Bulk Reports": "批量生成报告",
    "Generated Reports": "已生成报告",
    Preview: "预览",
    Locate: "在文件夹中显示",
    Open: "打开",
    Delete: "删除",
    "No generated reports yet.": "尚未生成报告。",
    "Report content settings": "报告内容设置",
    "Use saved content settings": "使用已保存的内容设置",
    "Select projects": "选择项目",
    "Select all": "全选",
    "Clear all": "清除选择",
    "Save content settings": "保存内容设置",
    "Content settings saved": "内容设置已保存",
    "All categories": "所有类别",
    "Inspect saved marketplace research or continue an active collection.": "查看已保存的市场研究或继续进行中的采集。",
    Inspect: "查看",
    "Continue Collection": "继续采集",
    "Collect Again": "重新采集",
    "Back to Projects": "返回项目",
    "Select a project": "选择项目",
    "No project": "没有项目",
    "Filename template": "文件名模板",
    "Filename preview": "文件名预览",
    "sections enabled": "个部分已启用",
    "Generating Report": "正在生成报告",
    "Rendering report and export files": "正在渲染报告和导出文件",
    "Report generation complete": "报告生成完成",
    "This report is still being prepared. Final export actions will become available when generation completes.": "报告仍在准备中。生成完成后即可使用最终导出操作。",
    "Search projects": "搜索项目",
    Uncategorized: "未分类",
    "No matching projects.": "没有匹配的项目。",
    "Bulk report history": "批量报告历史",
    "No bulk reports generated yet.": "尚未生成批量报告。",
    "Bulk report ready": "批量报告已就绪",
    "Configure the evidence sections used by single and bulk reports.": "配置单个和批量报告使用的证据部分。",
    "Back to projects": "返回项目",
    "Saved Collection Progress": "已保存的采集进度",
    "Saved URL": "已保存网址",
    "No browser URL saved": "未保存浏览器网址",
    "Current Step": "当前步骤",
    "View Mode": "视图模式",
    "Not selected": "未选择",
    Default: "默认",
    Media: "媒体",
    Products: "产品",
    Stores: "店铺",
    Reviews: "评论",
    "Price Range": "价格区间",
    "products with price evidence": "个具有价格证据的产品",
    "collected marketplace stores": "已采集的电商店铺",
    "Synthesized marketplace competition evidence": "综合电商竞争证据",
    "Generated with": "生成方式",
    "Generate this section from the saved project evidence and configured AI provider.": "使用已保存的项目证据和已配置的 AI 提供商生成此部分。",
    Regenerate: "重新生成",
    "Configure an OpenAI or Gemini API key in Settings before generating this AI-only section.": "请先在设置中配置 OpenAI 或 Gemini API 密钥，再生成此 AI 专属部分。",
    "Product Name": "产品名称",
    "USP / Key Claim": "USP / 核心主张",
    "Short Description": "简短描述",
    "Synthesized Category Insights": "综合品类洞察",
    "AI competition analysis is ready to generate": "AI 竞争分析已可生成",
    "The generated matrix and five specialist insights will also be used by report exports.": "生成的矩阵和五项专家洞察也将用于报告导出。",
    "Analysis Session": "分析会话",
    "Expand analysis session": "展开分析会话",
    "Collapse analysis session": "收起分析会话",
    Keyword: "关键词",
    Category: "类别",
    Platform: "平台",
    Created: "创建时间",
    "Collection Progress": "采集进度",
    "Key Product List": "重点产品列表",
    "Store Page List": "店铺页面列表",
    "Part 1": "第 1 部分",
    "Part 2": "第 2 部分",
    "Part 3": "第 3 部分",
    "Part 1 - Keyword General": "第 1 部分 - 关键词概览",
    "Part 2 - Product Details": "第 2 部分 - 产品详情",
    "Part 3 - Key Store Pages": "第 3 部分 - 重点店铺页面",
    "steps in this part": "本部分步骤",
    total: "总计",
    Overview: "概览",
    "AI evidence analysis": "AI 证据分析",
    "Evidence-based overview": "基于证据的概览",
    "Analyzing current evidence…": "正在分析当前证据…",
    "Key Store Page List": "重点店铺页面列表",
    "store pages": "个店铺页面",
    "Each store keeps its own homepage, profile, ratings, categories, products, banner, and TikTok evidence.": "每个店铺分别保存主页、资料、评分、类别、产品、横幅和 TikTok 证据。",
    "Continue Store Collection": "继续采集店铺",
    "No store pages yet. Approve qualified products or add a store page first.": "尚无店铺页面。请先批准合格产品或添加店铺页面。",
    Followers: "粉丝",
    Following: "关注",
    Rating: "评分",
    "Chat Performance": "聊天表现",
    Joined: "入驻时间",
    "Description Store": "店铺描述",
    "No store rating samples collected. Desktop view is recommended for this collector.": "尚未采集店铺评分样本。建议使用桌面视图进行此项采集。",
    "Desktop view is recommended for collecting store ratings.": "建议使用桌面视图采集店铺评分。",
    "Open rated product": "打开已评分产品",
    "Product link unavailable": "产品链接不可用",
    "Attached media": "附件媒体",
    Product: "产品",
    Comment: "评论",
    "Seller response": "卖家回复",
    No: "序号",
    "Category Name": "类别名称",
    "Total Product": "产品总数",
    "Loading settings.": "正在加载设置。",
    General: "常规",
    "AI Configuration": "AI 配置",
    Theme: "主题",
    Dark: "深色",
    Light: "浅色",
    "Preferred Browser": "首选浏览器",
    "not detected": "未检测到",
    "Export folder": "导出文件夹",
    "Choose report export folder": "选择报告导出文件夹",
    "Reset report export folder to default": "将报告导出文件夹恢复为默认值",
    "Screenshot folder": "截图文件夹",
    "Choose screenshot folder": "选择截图文件夹",
    "Reset screenshot folder to default": "将截图文件夹恢复为默认值",
    Concurrency: "并发数",
    "Report filename template": "报告文件名模板",
    "Save Settings": "保存设置",
    Runtime: "运行环境",
    "Marketplace adapters": "市场适配器",
    "Local database": "本地数据库",
    Application: "应用程序",
    Version: "版本",
    Packaged: "已打包",
    "Yes value": "是",
    "No value": "否",
    folders: "文件夹",
    Data: "数据",
    "Browser profiles": "浏览器配置文件",
    "Open App Folder": "打开应用文件夹",
    "OpenAI API key": "OpenAI API 密钥",
    "Gemini API key": "Gemini API 密钥",
    "Save AI Configuration": "保存 AI 配置",
    "AI API Key Setup": "AI API 密钥设置",
    "API keys are secrets. Keep each key private, do not place it in screenshots or source control, and rotate it immediately if it is exposed.": "API 密钥属于机密信息。请妥善保管，不要出现在截图或源代码管理中；如有泄露，请立即轮换。",
    "Official provider setup": "官方提供商设置",
    Configured: "已配置",
    "Not configured": "未配置",
    "Official guide": "官方指南",
    "Open OpenAI API Keys": "打开 OpenAI API 密钥",
    "Open Gemini API Keys": "打开 Gemini API 密钥",
    "Open the OpenAI API Keys page and sign in.": "打开 OpenAI API 密钥页面并登录。",
    "Select Create new secret key and copy it when it is shown.": "选择创建新的密钥，并在显示时复制。",
    "Paste it into OpenAI API key above, then save settings.": "将其粘贴到上方的 OpenAI API 密钥字段，然后保存设置。",
    "Open the Gemini API Keys page and sign in with your Google account.": "打开 Gemini API 密钥页面并使用 Google 账号登录。",
    "Select Create API key, choose a project, and copy the generated key.": "选择创建 API 密钥，选择一个项目，然后复制生成的密钥。",
    "Paste it into Gemini API key above, then save settings.": "将其粘贴到上方的 Gemini API 密钥字段，然后保存设置。",
    "Expand sidebar": "展开侧边栏",
    "Collapse sidebar": "收起侧边栏",
    "Primary navigation": "主导航",
    Available: "可用",
    "Keyword projects, screenshots, reports, browser sessions, and keys stay on this machine.": "关键词项目、截图、报告、浏览器会话和密钥均保留在本机。",
    "Developer profile": "开发者资料",
    Developer: "开发者",
    "Open developer profile": "打开开发者资料",
    Completed: "已完成",
    Incomplete: "未完成"
  }
};

export function isAppLanguage(value: unknown): value is AppLanguage {
  return value === "en-US" || value === "id-ID" || value === "zh-CN";
}

export function translate(language: AppLanguage, source: string): string {
  if (language === "en-US") {
    return source;
  }
  return TRANSLATIONS[language][source] ?? source;
}

export function languageOption(language: AppLanguage): AppLanguageOption {
  return APP_LANGUAGES.find((option) => option.id === language) ?? APP_LANGUAGES[0];
}
