export type AppLanguage = "id-ID" | "en-US" | "zh-CN";

export type AppLanguageOption = {
  id: AppLanguage;
  label: string;
  nativeLabel: string;
  shortLabel: string;
  preview: string;
};

export const APP_LANGUAGES: AppLanguageOption[] = [
  {
    id: "en-US",
    label: "English",
    nativeLabel: "English",
    shortLabel: "EN",
    preview: "Research workspace"
  },
  {
    id: "id-ID",
    label: "Indonesian",
    nativeLabel: "Bahasa Indonesia",
    shortLabel: "ID",
    preview: "Ruang kerja riset"
  },
  {
    id: "zh-CN",
    label: "Chinese",
    nativeLabel: "简体中文",
    shortLabel: "中文",
    preview: "市场研究工作区"
  }
];

const TRANSLATIONS: Record<Exclude<AppLanguage, "en-US">, Record<string, string>> = {
  "id-ID": {
    "Research Workspace": "Ruang Kerja Riset",
    "Keyword Projects": "Proyek Kata Kunci",
    Reports: "Laporan",
    Settings: "Pengaturan",
    Research: "Riset",
    Library: "Pustaka",
    System: "Sistem",
    "New Research": "Riset Baru",
    "Local Evidence Vault": "Brankas Bukti Lokal",
    "Open Settings": "Buka Pengaturan",
    "Add feedback": "Tambah masukan",
    "Send feedback": "Kirim masukan",
    "Employee ID feedback to": "ID karyawan tujuan masukan",
    "Lark / Tencent Mail": "Lark / Tencent Mail",
    "Contact developer for license key": "Hubungi developer untuk kunci lisensi",
    "Built by": "Dibangun oleh",
    "Marketplace Intelligence OS": "Marketplace Intelligence OS",
    "Research Product Market": "Research Product Market",
    "Clear search": "Hapus pencarian",
    Home: "Beranda",
    Language: "Bahasa",
    "Switch theme": "Ganti tema",
    "Light theme": "Tema terang",
    "Dark theme": "Tema gelap",
    "Create Analysis": "Buat Analisis",
    "Open setup": "Buka pengaturan riset",
    "Start a guided marketplace evidence session. You control the browser, the app captures each required report step.": "Mulai sesi bukti marketplace terpandu. Anda mengendalikan browser, dan aplikasi merekam setiap langkah laporan yang diperlukan.",
    "Desired Keyword": "Kata Kunci",
    "Product Category": "Kategori Produk",
    "Date Created": "Tanggal Dibuat",
    "Collection Platform": "Platform Koleksi",
    "Shop Type": "Jenis Toko",
    "Price Range (IDR)": "Rentang Harga (IDR)",
    "Coming soon": "Segera hadir",
    Minimum: "Minimum",
    Maximum: "Maksimum",
    to: "hingga",
    "Maximum price must be greater than or equal to minimum price.": "Harga maksimum harus lebih besar atau sama dengan harga minimum.",
    "Start Collection": "Mulai Koleksi",
    "Back": "Kembali",
    "Report Generator": "Generator Laporan",
    "Generate reports from saved marketplace evidence.": "Buat laporan dari bukti marketplace yang tersimpan.",
    "Report language": "Bahasa laporan",
    "Report structure": "Struktur laporan",
    "Drag sections to reorder the generated document.": "Seret bagian untuk mengubah urutan dokumen yang dibuat.",
    "DOCX preview": "Pratinjau DOCX",
    "Evidence-grounded specialist recommendations": "Rekomendasi spesialis berbasis bukti",
    "Configure OpenAI, Gemini, or Claude to enable specialist intelligence recommendations.": "Konfigurasikan OpenAI, Gemini, atau Claude untuk mengaktifkan rekomendasi intelijen spesialis.",
    "No report sections selected.": "Belum ada bagian laporan yang dipilih.",
    "Single Report": "Laporan Tunggal",
    "Bulk Report": "Laporan Massal",
    Project: "Proyek",
    Projects: "Proyek",
    "File types": "Jenis file",
    "Where to save": "Lokasi penyimpanan",
    "Choose folder": "Pilih folder",
    "Choose Report Content": "Pilih Isi Laporan",
    Edit: "Edit",
    Save: "Simpan",
    Cancel: "Batal",
    Generate: "Buat",
    "Generate Report": "Buat Laporan",
    "Generate Bulk Reports": "Buat Laporan Massal",
    "Generated Reports": "Laporan Tersimpan",
    Preview: "Pratinjau",
    Locate: "Tampilkan lokasi",
    Open: "Buka",
    Delete: "Hapus",
    "No generated reports yet.": "Belum ada laporan yang dibuat.",
    "Report content settings": "Pengaturan isi laporan",
    "Use saved content settings": "Gunakan pengaturan isi tersimpan",
    "Select projects": "Pilih proyek",
    "Select all": "Pilih semua",
    "Clear all": "Hapus pilihan",
    "Save content settings": "Simpan pengaturan isi",
    "Content settings saved": "Pengaturan isi tersimpan",
    "All categories": "Semua kategori",
    "Inspect saved marketplace research or continue an active collection.": "Periksa riset marketplace tersimpan atau lanjutkan koleksi aktif.",
    Inspect: "Periksa",
    "Continue Collection": "Lanjutkan Koleksi",
    "Collect Again": "Koleksi Ulang",
    "Back to Projects": "Kembali ke Proyek",
    "Select a project": "Pilih proyek",
    "No project": "Tidak ada proyek",
    "Filename template": "Templat nama file",
    "Filename preview": "Pratinjau nama file",
    "sections enabled": "bagian aktif",
    "Generating Report": "Membuat Laporan",
    "Rendering report and export files": "Merender laporan dan file ekspor",
    "Report generation complete": "Pembuatan laporan selesai",
    "Report generation failed": "Pembuatan laporan gagal",
    "This report is still being prepared. Final export actions will become available when generation completes.": "Laporan ini masih diproses. Aksi ekspor akhir akan tersedia setelah proses selesai.",
    "Search projects": "Cari proyek",
    Uncategorized: "Tanpa kategori",
    "No matching projects.": "Tidak ada proyek yang cocok.",
    "Bulk report history": "Riwayat laporan massal",
    "No bulk reports generated yet.": "Belum ada laporan massal yang dibuat.",
    "Bulk report ready": "Laporan massal siap",
    "Configure the evidence sections used by single and bulk reports.": "Atur bagian bukti yang digunakan oleh laporan tunggal dan massal.",
    "Back to projects": "Kembali ke proyek",
    "Back to project": "Kembali ke proyek",
    "Expand collection drawer": "Buka drawer koleksi",
    "Collapse collection drawer": "Tutup drawer koleksi",
    "Mark as complete": "Tandai selesai",
    "Marked complete:": "Ditandai selesai:",
    "Why is this action complete?": "Mengapa tindakan ini dianggap selesai?",
    "Add the evidence, limitation, or decision context.": "Tambahkan konteks bukti, keterbatasan, atau keputusan.",
    "Confirm complete": "Konfirmasi selesai",
    "Saved Collection Progress": "Progres Koleksi Tersimpan",
    "Saved URL": "URL Tersimpan",
    "No browser URL saved": "Tidak ada URL browser tersimpan",
    "Current Step": "Langkah Saat Ini",
    "View Mode": "Mode Tampilan",
    "Not selected": "Belum dipilih",
    Default: "Standar",
    Media: "Media",
    Products: "Produk",
    Stores: "Toko",
    Reviews: "Ulasan",
    "Price Range": "Rentang Harga",
    "products with price evidence": "produk dengan bukti harga",
    "collected marketplace stores": "toko marketplace yang dikoleksi",
    "Synthesized marketplace competition evidence": "Sintesis bukti persaingan marketplace",
    "Generated with": "Dihasilkan dengan",
    "Generate this section from the saved project evidence and configured AI provider.": "Buat bagian ini dari bukti proyek tersimpan dan penyedia AI yang telah dikonfigurasi.",
    Regenerate: "Buat Ulang",
    "Configure an OpenAI, Gemini, or Claude API key in Settings before generating this AI-only section.": "Konfigurasikan kunci API OpenAI, Gemini, atau Claude di Pengaturan sebelum membuat bagian khusus AI ini.",
    "Product Name": "Nama Produk",
    "USP / Key Claim": "USP / Klaim Utama",
    "Short Description": "Deskripsi Singkat",
    "Synthesized Category Insights": "Sintesis Insight Kategori",
    "AI competition analysis is ready to generate": "Analisis persaingan AI siap dibuat",
    "The generated matrix and five specialist insights will also be used by report exports.": "Matriks dan lima insight spesialis yang dibuat juga akan digunakan dalam ekspor laporan.",
    "Analysis Session": "Sesi Analisis",
    "Expand analysis session": "Perluas sesi analisis",
    "Collapse analysis session": "Ciutkan sesi analisis",
    Keyword: "Kata Kunci",
    Category: "Kategori",
    Platform: "Platform",
    Created: "Dibuat",
    "Collection Progress": "Progres Koleksi",
    "Project sections": "Bagian proyek",
    "Show project outline": "Tampilkan kerangka proyek",
    "Hide project outline": "Sembunyikan kerangka proyek",
    "Keyword General": "Kata Kunci Umum",
    Relevance: "Relevansi",
    "Top Sales": "Penjualan Teratas",
    "Top sales": "Penjualan teratas",
    "Key Product": "Produk Utama",
    "Product info": "Informasi produk",
    "Product Detail Qualified": "Detail Produk Terpilih",
    "Product Detailed Qualified": "Detail Produk Terpilih",
    "First page": "Halaman pertama",
    "Slides and images": "Slide dan gambar",
    Description: "Deskripsi",
    "Media in user": "Media pengguna",
    "Shop homepage": "Beranda toko",
    "Store Home Page": "Beranda Toko",
    "Store Data": "Data Toko",
    "1 Star Store Ratings": "Ulasan Toko 1 Bintang",
    "5 Star Store Ratings": "Ulasan Toko 5 Bintang",
    "Store Product Categories": "Kategori Produk Toko",
    "Popular Products": "Produk Populer",
    "Store Best Sellers": "Produk Terlaris Toko",
    "Visual Shop Banner": "Banner Visual Toko",
    "TikTok Evidence": "Bukti TikTok",
    "Keyword Search Analysis & Top 10 Competition Matrix": "Analisis Pencarian Kata Kunci & Matriks 10 Kompetitor Teratas",
    "Key Product List": "Daftar Produk Utama",
    "Store Page List": "Daftar Halaman Toko",
    "Part 1": "Bagian 1",
    "Part 2": "Bagian 2",
    "Part 3": "Bagian 3",
    "Part 1 - Keyword General": "Bagian 1 - Kata Kunci Umum",
    "Part 2 - Product Details": "Bagian 2 - Detail Produk",
    "Part 3 - Key Store Pages": "Bagian 3 - Halaman Toko Utama",
    "steps in this part": "langkah di bagian ini",
    total: "total",
    Overview: "Ringkasan",
    "AI evidence analysis": "Analisis bukti AI",
    "Evidence-based overview": "Ringkasan berbasis bukti",
    "Analyzing current evidence…": "Menganalisis bukti saat ini…",
    "Key Store Page List": "Daftar Halaman Toko Utama",
    "store pages": "halaman toko",
    "Each store keeps its own homepage, profile, ratings, categories, products, banner, and TikTok evidence.": "Setiap toko menyimpan beranda, profil, penilaian, kategori, produk, banner, dan bukti TikTok secara terpisah.",
    "Continue Store Collection": "Lanjutkan Koleksi Toko",
    "No store pages yet. Approve qualified products or add a store page first.": "Belum ada halaman toko. Setujui produk yang memenuhi syarat atau tambahkan halaman toko terlebih dahulu.",
    Followers: "Pengikut",
    Following: "Mengikuti",
    Rating: "Penilaian",
    "Chat Performance": "Performa Chat",
    Joined: "Bergabung",
    "Description Store": "Deskripsi Toko",
    "No store rating samples collected. Desktop view is recommended for this collector.": "Belum ada sampel penilaian toko yang dikoleksi. Tampilan desktop disarankan untuk kolektor ini.",
    "Desktop view is recommended for collecting store ratings.": "Tampilan desktop disarankan untuk mengoleksi penilaian toko.",
    "Open rated product": "Buka produk yang dinilai",
    "Product link unavailable": "Tautan produk tidak tersedia",
    "Attached media": "Media terlampir",
    Product: "Produk",
    Comment: "Komentar",
    "Seller response": "Respons penjual",
    No: "No",
    "Category Name": "Nama Kategori",
    "Total Product": "Total Produk",
    "Loading settings.": "Memuat pengaturan.",
    General: "Umum",
    "AI Configuration": "Konfigurasi AI",
    Theme: "Tema",
    Dark: "Gelap",
    Light: "Terang",
    "Preferred Browser": "Browser Pilihan",
    "not detected": "tidak terdeteksi",
    "Export folder": "Folder ekspor",
    "Choose report export folder": "Pilih folder ekspor laporan",
    "Reset report export folder to default": "Kembalikan folder ekspor laporan ke standar",
    "Screenshot folder": "Folder tangkapan layar",
    "Choose screenshot folder": "Pilih folder tangkapan layar",
    "Reset screenshot folder to default": "Kembalikan folder tangkapan layar ke standar",
    Concurrency: "Proses Bersamaan",
    "Report filename template": "Templat nama file laporan",
    "Save Settings": "Simpan Pengaturan",
    Runtime: "Runtime",
    "Marketplace adapters": "Adaptor marketplace",
    "Local database": "Database lokal",
    Application: "Aplikasi",
    Version: "Versi",
    Packaged: "Dikemas",
    "Yes value": "Ya",
    "No value": "Tidak",
    folders: "folder",
    Data: "Data",
    "Browser profiles": "Profil browser",
    "Open App Folder": "Buka Folder Aplikasi",
    "OpenAI API key": "Kunci API OpenAI",
    "Gemini API key": "Kunci API Gemini",
    "Save AI Configuration": "Simpan Konfigurasi AI",
    "AI API Key Setup": "Pengaturan Kunci API AI",
    "API keys are secrets. Keep each key private, do not place it in screenshots or source control, and rotate it immediately if it is exposed.": "Kunci API bersifat rahasia. Jaga setiap kunci tetap privat, jangan tampilkan dalam tangkapan layar atau kontrol sumber, dan segera ganti jika terekspos.",
    "Official provider setup": "Pengaturan penyedia resmi",
    Configured: "Terkonfigurasi",
    "Not configured": "Belum dikonfigurasi",
    "Official guide": "Panduan resmi",
    "Open OpenAI API Keys": "Buka Kunci API OpenAI",
    "Open Gemini API Keys": "Buka Kunci API Gemini",
    "Open the OpenAI API Keys page and sign in.": "Buka halaman Kunci API OpenAI lalu masuk.",
    "Select Create new secret key and copy it when it is shown.": "Pilih Buat kunci rahasia baru lalu salin saat ditampilkan.",
    "Paste it into OpenAI API key above, then save settings.": "Tempel ke kolom kunci API OpenAI di atas, lalu simpan pengaturan.",
    "Open the Gemini API Keys page and sign in with your Google account.": "Buka halaman Kunci API Gemini lalu masuk dengan akun Google Anda.",
    "Select Create API key, choose a project, and copy the generated key.": "Pilih Buat kunci API, pilih proyek, lalu salin kunci yang dibuat.",
    "Paste it into Gemini API key above, then save settings.": "Tempel ke kolom kunci API Gemini di atas, lalu simpan pengaturan.",
    "Expand sidebar": "Perluas sidebar",
    "Collapse sidebar": "Ciutkan sidebar",
    "Primary navigation": "Navigasi utama",
    Available: "Tersedia",
    "Keyword projects, screenshots, reports, browser sessions, and keys stay on this machine.": "Proyek kata kunci, tangkapan layar, laporan, sesi browser, dan kunci tetap tersimpan di perangkat ini.",
    "Developer profile": "Profil pengembang",
    Developer: "Pengembang",
    "Open developer profile": "Buka profil pengembang",
    Ready: "Siap",
    Deleting: "Menghapus",
    Mobile: "Seluler",
    Desktop: "Desktop",
    Actions: "Tindakan",
    Select: "Pilih",
    Source: "Sumber",
    Reason: "Alasan",
    "Product Title": "Judul Produk",
    "Product Type": "Jenis Produk",
    "Monthly Sold": "Terjual Bulanan",
    "Store Name": "Nama Toko",
    "Store Type": "Jenis Toko",
    Price: "Harga",
    "Total Sold": "Total Terjual",
    products: "produk",
    stores: "toko",
    complete: "selesai",
    "No category": "Tanpa kategori",
    "All shop types": "Semua jenis toko",
    "All prices": "Semua harga",
    From: "Mulai",
    "Up to": "Hingga",
    "No minimum": "Tanpa minimum",
    "No maximum": "Tanpa maksimum",
    "Market Scope": "Cakupan Pasar",
    "Applied filters & market coverage": "Filter aktif & cakupan pasar",
    "Collected marketplace stores": "Toko marketplace terkoleksi",
    "Shop type": "Jenis toko",
    "Price range": "Rentang harga",
    "Product evidence": "Bukti produk",
    "Shop Type Filters": "Filter Jenis Toko",
    "Delete project": "Hapus proyek",
    "Delete keyword project?": "Hapus proyek kata kunci?",
    "This permanently removes the project, evidence, reports, and local files. Type": "Tindakan ini menghapus proyek, bukti, laporan, dan file lokal secara permanen. Ketik",
    "to confirm.": "untuk mengonfirmasi.",
    "Project name confirmation": "Konfirmasi nama proyek",
    "Card view": "Tampilan kartu",
    "List view": "Tampilan daftar",
    "Marketplace product evidence": "Bukti produk marketplace",
    "Store pending": "Toko belum tersedia",
    "Preview product image": "Pratinjau gambar produk",
    "Product image preview": "Pratinjau gambar produk",
    "Rating evidence": "Bukti penilaian",
    "Store rating evidence preview": "Pratinjau bukti penilaian toko",
    "File preview": "Pratinjau file",
    "Show in folder": "Tampilkan di folder",
    "DOCX document preview": "Pratinjau dokumen DOCX",
    Slide: "Slide",
    "Remove product": "Hapus produk",
    "Zoom in": "Perbesar",
    "Zoom out": "Perkecil",
    "Use Ctrl/Command + wheel to zoom, then drag to pan.": "Gunakan Ctrl/Command + roda mouse untuk memperbesar, lalu seret untuk menggeser.",
    "Monthly sold only applies to Top Sales result snapshots. Total sold is collected from PDP evidence when visible.": "Terjual bulanan hanya berlaku untuk cuplikan hasil Penjualan Teratas. Total terjual dikumpulkan dari bukti halaman detail produk saat terlihat.",
    "Rating is the star value; Reviews is the rating/review count. Price ranges are stored as estimated average price.": "Penilaian adalah nilai bintang; Ulasan adalah jumlah penilaian/ulasan. Rentang harga disimpan sebagai perkiraan harga rata-rata.",
    "Project Inspector": "Pemeriksa Proyek",
    "Loading project evidence...": "Memuat bukti proyek...",
    "No keyword projects match the current search and category.": "Tidak ada proyek kata kunci yang cocok dengan pencarian dan kategori saat ini.",
    "Capture Relevance and Top Sales first to generate dynamic product detail steps.": "Kumpulkan Relevansi dan Penjualan Teratas terlebih dahulu untuk membuat langkah detail produk dinamis.",
    "No collected data yet for this section.": "Belum ada data yang dikumpulkan untuk bagian ini.",
    "Preparing preview...": "Menyiapkan pratinjau...",
    "The PDF preview could not be displayed.": "Pratinjau PDF tidak dapat ditampilkan.",
    "No rendered product rows extracted yet.": "Belum ada baris produk yang berhasil diekstrak.",
    "Product info table is empty. Capture Relevance and Top Sales pages first.": "Tabel informasi produk kosong. Kumpulkan halaman Relevansi dan Penjualan Teratas terlebih dahulu.",
    "No product image URLs captured yet.": "Belum ada URL gambar produk yang dikumpulkan.",
    "No product video URLs captured yet.": "Belum ada URL video produk yang dikumpulkan.",
    "No review text collected yet. Capture the review section with 3 positive and 2 negative examples visible.": "Belum ada teks ulasan yang dikumpulkan. Ambil bagian ulasan dengan 3 contoh positif dan 2 contoh negatif yang terlihat.",
    "Store details have not been collected.": "Detail toko belum dikumpulkan.",
    "No store categories collected.": "Belum ada kategori toko yang dikumpulkan.",
    Activity: "Aktivitas",
    "Platform Browser": "Browser Platform",
    "TikTok Analysis Session": "Sesi Analisis TikTok",
    "Mobile Collection Steps": "Langkah Koleksi Seluler",
    "Android Emulator Workspace": "Ruang Kerja Emulator Android",
    "Bulk Report Generation": "Pembuatan Laporan Massal",
    "Select by category": "Pilih berdasarkan kategori",
    "No bulk report ZIP generated yet.": "Belum ada ZIP laporan massal yang dibuat.",
    "2. Choose Report Content": "2. Pilih Isi Laporan",
    "Key Product Table": "Tabel Produk Utama",
    Email: "Email",
    Password: "Kata sandi",
    "License key": "Kunci lisensi",
    Completed: "Selesai",
    Incomplete: "Belum selesai",
    "Activate Research Product Market": "Aktifkan Research Product Market",
    "Enter the email, password, and signed license issued for this device.": "Masukkan email, kata sandi, dan lisensi bertanda tangan yang diterbitkan untuk perangkat ini.",
    "Activate and sign in": "Aktifkan dan masuk",
    "Verifying license": "Memverifikasi lisensi",
    "Machine ID:": "ID Mesin:",
    "Marketplace research and evidence workspace": "Ruang kerja riset dan bukti marketplace",
    "Made by": "Dibuat oleh",
    "Launch Android, install or open TikTok, log in with Gmail if needed, then enter TikTok Shop manually. Closing the emulator keeps the AVD data partition, installed apps, and login state.": "Jalankan Android, instal atau buka TikTok, masuk dengan Gmail jika diperlukan, lalu buka TikTok Shop secara manual. Menutup emulator tetap mempertahankan data AVD, aplikasi, dan status login.",
    Step: "Langkah",
    Refresh: "Segarkan",
    "Emulator launch is persistent by design. The app does not wipe Android, uninstall TikTok, clear app data, or reset Google login when the emulator is closed.": "Emulator dirancang persisten. Aplikasi tidak menghapus Android, mencopot TikTok, menghapus data aplikasi, atau mereset login Google saat emulator ditutup.",
    "TikTok is not responding": "TikTok tidak merespons",
    "Android reported an ANR in TikTok. Recovery force-stops and reopens TikTok only; it keeps the emulator profile, installed app, and account data intact.": "Android melaporkan TikTok tidak merespons. Pemulihan hanya menghentikan paksa dan membuka ulang TikTok tanpa mengubah profil emulator, aplikasi, atau data akun.",
    "Active Step": "Langkah Aktif",
    "Manual action required": "Tindakan manual diperlukan",
    "Shopee is showing login, verification, captcha, or a protected page. Complete it manually, then capture evidence after the target page is visible.": "Shopee menampilkan login, verifikasi, captcha, atau halaman terlindungi. Selesaikan secara manual, lalu ambil bukti setelah halaman target terlihat.",
    "Preview: Key Product Table": "Pratinjau: Tabel Produk Utama",
    "selected from": "dipilih dari",
    "extracted rows.": "baris yang diekstrak.",
    Type: "Jenis",
    Star: "Bintang",
    "Comment - timepost": "Komentar - waktu kirim",
    "Description preview": "Pratinjau deskripsi",
    "Live store result preview": "Pratinjau langsung hasil toko",
    "Step Actions": "Tindakan Langkah",
    Updating: "Memperbarui",
    Browser: "Browser",
    "Every distinct store from Product Qualified is listed once. Review the list, add another Shopee store when needed, then collect each store page independently.": "Setiap toko unik dari Produk Terpilih hanya ditampilkan sekali. Tinjau daftar, tambahkan toko Shopee bila perlu, lalu kumpulkan setiap halaman toko secara terpisah.",
    "Key Store Page": "Halaman Toko Utama",
    "Shop ID": "ID Toko",
    "Add Store Page": "Tambah Halaman Toko",
    "Add store page": "Tambah halaman toko",
    "Store name": "Nama toko",
    "Shopee store URL": "URL toko Shopee",
    Add: "Tambah",
    "Save Store List": "Simpan Daftar Toko",
    "Manually added": "Ditambahkan manual",
    "Add at least one Key Store Page to continue.": "Tambahkan minimal satu Halaman Toko Utama untuk melanjutkan.",
    "Guided Collection": "Koleksi Terpandu",
    "Recommended:": "Disarankan:",
    "Open Target": "Buka Target",
    "Open the matching product page before collecting Product Detail data.": "Buka halaman produk yang sesuai sebelum mengumpulkan data Detail Produk.",
    "Open TikTok": "Buka TikTok",
    "Attach Shot": "Lampirkan Tangkapan",
    "Review Screenshot": "Tinjau Tangkapan Layar",
    "Save Full": "Simpan Penuh",
    Redo: "Ulangi",
    "Scroll to move through the preview. Use zoom buttons or Ctrl/Command + wheel to zoom, then drag to pan. Use Select Area before dragging a crop box.": "Gulir untuk menjelajahi pratinjau. Gunakan tombol zoom atau Ctrl/Command dan roda mouse, lalu seret untuk menggeser. Aktifkan Pilih Area sebelum menarik kotak potong.",
    "Product Qualified starts with Top Sales evidence, then uses Relevance evidence to enrich and rank commercially valid products.": "Produk Terpilih dimulai dari bukti Penjualan Teratas, lalu memakai bukti Relevansi untuk memperkaya dan memberi peringkat produk yang layak secara komersial.",
    "GIMMICK, NOT FOR SALE, FREE GIFT, irrelevant, and duplicate rows are excluded. Review up to 20 products before approval.": "Baris GIMMICK, TIDAK DIJUAL, HADIAH GRATIS, tidak relevan, dan duplikat dikecualikan. Tinjau hingga 20 produk sebelum persetujuan.",
    Showing: "Menampilkan",
    from: "dari",
    selected: "dipilih",
    "Exclude selected": "Kecualikan pilihan",
    "Add another qualified product": "Tambah produk terpilih lain",
    "Select product": "Pilih produk",
    "Add Product": "Tambah Produk",
    "Add 5 more product": "Tambah 5 produk lagi",
    "Available products": "Produk tersedia",
    "Add selected": "Tambah pilihan",
    "Maximum 20 qualified products reached.": "Batas maksimum 20 produk terpilih telah tercapai.",
    "Store Name, Total Sold, review detail, slides, description, and shop homepage are enriched during Product Detail Qualified collection.": "Nama Toko, Total Terjual, detail ulasan, slide, deskripsi, dan beranda toko diperkaya saat koleksi Detail Produk Terpilih.",
    Next: "Berikutnya",
    "No promotion signal captured yet.": "Belum ada sinyal promosi yang dikumpulkan.",
    "Slides and Images": "Slide dan Gambar",
    Videos: "Video",
    "Media in User": "Media Pengguna",
    Variants: "Varian",
    "No variants detected.": "Tidak ada varian terdeteksi.",
    Specifications: "Spesifikasi",
    "No specifications detected.": "Tidak ada spesifikasi terdeteksi.",
    Video: "Video",
    "Star Rated": "Peringkat Bintang",
    "Comment - Include timestamp": "Komentar - Sertakan waktu",
    "Choose a category": "Pilih kategori",
    "Select multiple projects from": "Pilih beberapa proyek dari",
    "files packaged in": "file dikemas di",
    "Open ZIP": "Buka ZIP",
    "Bulk Report History": "Riwayat Laporan Massal",
    projects: "proyek",
    files: "file",
    "Report generated at": "Laporan dibuat di",
    "Enable the sections needed in the final report. Drag section groups to reorder them.": "Aktifkan bagian yang diperlukan dalam laporan akhir. Seret grup bagian untuk mengubah urutannya.",
    of: "dari",
    enabled: "aktif",
    "Drag this parent section to change report order.": "Seret bagian induk ini untuk mengubah urutan laporan.",
    "Report Preview": "Pratinjau Laporan",
    "Preview report": "Pratinjau laporan",
    "Open DOCX": "Buka DOCX",
    "Open HTML": "Buka HTML",
    "Preview zoom controls": "Kontrol zoom pratinjau",
    "Rendering DOCX preview...": "Merender pratinjau DOCX...",
    "DOCX pages": "Halaman DOCX",
    "Collapse report navigation": "Tutup navigasi laporan",
    "Expand report navigation": "Buka navigasi laporan",
    "Report preview": "Pratinjau laporan",
    "Report headings": "Judul laporan",
    Contents: "Daftar Isi",
    "Close report preview": "Tutup pratinjau laporan",
    "Launch Emulator": "Jalankan Emulator",
    "Select APK": "Pilih APK",
    "Install TikTok": "Instal TikTok",
    "Open TikTok App": "Buka Aplikasi TikTok"
  },
  "zh-CN": {
    "Research Workspace": "市场研究工作区",
    "Keyword Projects": "关键词项目",
    Reports: "报告",
    Settings: "设置",
    Research: "研究",
    Library: "资料库",
    System: "系统",
    "New Research": "新建研究",
    "Local Evidence Vault": "本地证据库",
    "Open Settings": "打开设置",
    "Add feedback": "添加反馈",
    "Send feedback": "发送反馈",
    "Employee ID feedback to": "反馈员工编号",
    "Lark / Tencent Mail": "Lark / 腾讯邮箱",
    "Contact developer for license key": "联系开发者获取许可证密钥",
    "Built by": "构建者",
    "Marketplace Intelligence OS": "Marketplace Intelligence OS",
    "Research Product Market": "产品市场研究",
    "Clear search": "清除搜索",
    Home: "首页",
    Language: "语言",
    "Switch theme": "切换主题",
    "Light theme": "浅色主题",
    "Dark theme": "深色主题",
    "Create Analysis": "创建分析",
    "Open setup": "打开研究设置",
    "Start a guided marketplace evidence session. You control the browser, the app captures each required report step.": "开始引导式市场证据会话。您控制浏览器，应用会记录报告所需的每个步骤。",
    "Desired Keyword": "目标关键词",
    "Product Category": "产品类别",
    "Date Created": "创建日期",
    "Collection Platform": "采集平台",
    "Shop Type": "店铺类型",
    "Price Range (IDR)": "价格范围（IDR）",
    "Coming soon": "即将推出",
    Minimum: "最低",
    Maximum: "最高",
    to: "至",
    "Maximum price must be greater than or equal to minimum price.": "最高价格必须大于或等于最低价格。",
    "Start Collection": "开始采集",
    "Back": "返回",
    "Report Generator": "报告生成器",
    "Generate reports from saved marketplace evidence.": "从已保存的市场证据生成报告。",
    "Report language": "报告语言",
    "Report structure": "报告结构",
    "Drag sections to reorder the generated document.": "拖动章节以调整生成文档的顺序。",
    "DOCX preview": "DOCX 预览",
    "Evidence-grounded specialist recommendations": "基于证据的专业建议",
    "Configure OpenAI, Gemini, or Claude to enable specialist intelligence recommendations.": "配置 OpenAI、Gemini 或 Claude 以启用专业市场情报建议。",
    "No report sections selected.": "尚未选择报告章节。",
    "Single Report": "单个报告",
    "Bulk Report": "批量报告",
    Project: "项目",
    Projects: "项目",
    "File types": "文件类型",
    "Where to save": "保存位置",
    "Choose folder": "选择文件夹",
    "Choose Report Content": "选择报告内容",
    Edit: "编辑",
    Save: "保存",
    Cancel: "取消",
    Generate: "生成",
    "Generate Report": "生成报告",
    "Generate Bulk Reports": "批量生成报告",
    "Generated Reports": "已生成报告",
    Preview: "预览",
    Locate: "在文件夹中显示",
    Open: "打开",
    Delete: "删除",
    "No generated reports yet.": "尚未生成报告。",
    "Report content settings": "报告内容设置",
    "Use saved content settings": "使用已保存的内容设置",
    "Select projects": "选择项目",
    "Select all": "全选",
    "Clear all": "清除选择",
    "Save content settings": "保存内容设置",
    "Content settings saved": "内容设置已保存",
    "All categories": "所有类别",
    "Inspect saved marketplace research or continue an active collection.": "查看已保存的市场研究或继续进行中的采集。",
    Inspect: "查看",
    "Continue Collection": "继续采集",
    "Collect Again": "重新采集",
    "Back to Projects": "返回项目",
    "Select a project": "选择项目",
    "No project": "没有项目",
    "Filename template": "文件名模板",
    "Filename preview": "文件名预览",
    "sections enabled": "个部分已启用",
    "Generating Report": "正在生成报告",
    "Rendering report and export files": "正在渲染报告和导出文件",
    "Report generation complete": "报告生成完成",
    "Report generation failed": "报告生成失败",
    "This report is still being prepared. Final export actions will become available when generation completes.": "报告仍在准备中。生成完成后即可使用最终导出操作。",
    "Search projects": "搜索项目",
    Uncategorized: "未分类",
    "No matching projects.": "没有匹配的项目。",
    "Bulk report history": "批量报告历史",
    "No bulk reports generated yet.": "尚未生成批量报告。",
    "Bulk report ready": "批量报告已就绪",
    "Configure the evidence sections used by single and bulk reports.": "配置单个和批量报告使用的证据部分。",
    "Back to projects": "返回项目",
    "Back to project": "返回项目",
    "Expand collection drawer": "展开采集抽屉",
    "Collapse collection drawer": "收起采集抽屉",
    "Mark as complete": "标记为完成",
    "Marked complete:": "已标记完成：",
    "Why is this action complete?": "为什么此操作已完成？",
    "Add the evidence, limitation, or decision context.": "添加证据、限制或决策背景。",
    "Confirm complete": "确认完成",
    "Saved Collection Progress": "已保存的采集进度",
    "Saved URL": "已保存网址",
    "No browser URL saved": "未保存浏览器网址",
    "Current Step": "当前步骤",
    "View Mode": "视图模式",
    "Not selected": "未选择",
    Default: "默认",
    Media: "媒体",
    Products: "产品",
    Stores: "店铺",
    Reviews: "评论",
    "Price Range": "价格区间",
    "products with price evidence": "个具有价格证据的产品",
    "collected marketplace stores": "已采集的电商店铺",
    "Synthesized marketplace competition evidence": "综合电商竞争证据",
    "Generated with": "生成方式",
    "Generate this section from the saved project evidence and configured AI provider.": "使用已保存的项目证据和已配置的 AI 提供商生成此部分。",
    Regenerate: "重新生成",
    "Configure an OpenAI, Gemini, or Claude API key in Settings before generating this AI-only section.": "请先在设置中配置 OpenAI、Gemini 或 Claude API 密钥，再生成此 AI 专属部分。",
    "Product Name": "产品名称",
    "USP / Key Claim": "USP / 核心主张",
    "Short Description": "简短描述",
    "Synthesized Category Insights": "综合品类洞察",
    "AI competition analysis is ready to generate": "AI 竞争分析已可生成",
    "The generated matrix and five specialist insights will also be used by report exports.": "生成的矩阵和五项专家洞察也将用于报告导出。",
    "Analysis Session": "分析会话",
    "Expand analysis session": "展开分析会话",
    "Collapse analysis session": "收起分析会话",
    Keyword: "关键词",
    Category: "类别",
    Platform: "平台",
    Created: "创建时间",
    "Collection Progress": "采集进度",
    "Project sections": "项目章节",
    "Show project outline": "显示项目大纲",
    "Hide project outline": "隐藏项目大纲",
    "Keyword General": "关键词概览",
    Relevance: "相关性",
    "Top Sales": "最高销量",
    "Top sales": "最高销量",
    "Key Product": "重点产品",
    "Product info": "产品信息",
    "Product Detail Qualified": "入选产品详情",
    "Product Detailed Qualified": "入选产品详情",
    "First page": "首页",
    "Slides and images": "轮播图与图片",
    Description: "描述",
    "Media in user": "用户媒体",
    "Shop homepage": "店铺首页",
    "Store Home Page": "店铺首页",
    "Store Data": "店铺数据",
    "1 Star Store Ratings": "1 星店铺评价",
    "5 Star Store Ratings": "5 星店铺评价",
    "Store Product Categories": "店铺产品分类",
    "Popular Products": "热门产品",
    "Store Best Sellers": "店铺畅销产品",
    "Visual Shop Banner": "店铺视觉横幅",
    "TikTok Evidence": "TikTok 证据",
    "Keyword Search Analysis & Top 10 Competition Matrix": "关键词搜索分析与前 10 名竞争矩阵",
    "Key Product List": "重点产品列表",
    "Store Page List": "店铺页面列表",
    "Part 1": "第 1 部分",
    "Part 2": "第 2 部分",
    "Part 3": "第 3 部分",
    "Part 1 - Keyword General": "第 1 部分 - 关键词概览",
    "Part 2 - Product Details": "第 2 部分 - 产品详情",
    "Part 3 - Key Store Pages": "第 3 部分 - 重点店铺页面",
    "steps in this part": "本部分步骤",
    total: "总计",
    Overview: "概览",
    "AI evidence analysis": "AI 证据分析",
    "Evidence-based overview": "基于证据的概览",
    "Analyzing current evidence…": "正在分析当前证据…",
    "Key Store Page List": "重点店铺页面列表",
    "store pages": "个店铺页面",
    "Each store keeps its own homepage, profile, ratings, categories, products, banner, and TikTok evidence.": "每个店铺分别保存主页、资料、评分、类别、产品、横幅和 TikTok 证据。",
    "Continue Store Collection": "继续采集店铺",
    "No store pages yet. Approve qualified products or add a store page first.": "尚无店铺页面。请先批准合格产品或添加店铺页面。",
    Followers: "粉丝",
    Following: "关注",
    Rating: "评分",
    "Chat Performance": "聊天表现",
    Joined: "入驻时间",
    "Description Store": "店铺描述",
    "No store rating samples collected. Desktop view is recommended for this collector.": "尚未采集店铺评分样本。建议使用桌面视图进行此项采集。",
    "Desktop view is recommended for collecting store ratings.": "建议使用桌面视图采集店铺评分。",
    "Open rated product": "打开已评分产品",
    "Product link unavailable": "产品链接不可用",
    "Attached media": "附件媒体",
    Product: "产品",
    Comment: "评论",
    "Seller response": "卖家回复",
    No: "序号",
    "Category Name": "类别名称",
    "Total Product": "产品总数",
    "Loading settings.": "正在加载设置。",
    General: "常规",
    "AI Configuration": "AI 配置",
    Theme: "主题",
    Dark: "深色",
    Light: "浅色",
    "Preferred Browser": "首选浏览器",
    "not detected": "未检测到",
    "Export folder": "导出文件夹",
    "Choose report export folder": "选择报告导出文件夹",
    "Reset report export folder to default": "将报告导出文件夹恢复为默认值",
    "Screenshot folder": "截图文件夹",
    "Choose screenshot folder": "选择截图文件夹",
    "Reset screenshot folder to default": "将截图文件夹恢复为默认值",
    Concurrency: "并发数",
    "Report filename template": "报告文件名模板",
    "Save Settings": "保存设置",
    Runtime: "运行环境",
    "Marketplace adapters": "市场适配器",
    "Local database": "本地数据库",
    Application: "应用程序",
    Version: "版本",
    Packaged: "已打包",
    "Yes value": "是",
    "No value": "否",
    folders: "文件夹",
    Data: "数据",
    "Browser profiles": "浏览器配置文件",
    "Open App Folder": "打开应用文件夹",
    "OpenAI API key": "OpenAI API 密钥",
    "Gemini API key": "Gemini API 密钥",
    "Save AI Configuration": "保存 AI 配置",
    "AI API Key Setup": "AI API 密钥设置",
    "API keys are secrets. Keep each key private, do not place it in screenshots or source control, and rotate it immediately if it is exposed.": "API 密钥属于机密信息。请妥善保管，不要出现在截图或源代码管理中；如有泄露，请立即轮换。",
    "Official provider setup": "官方提供商设置",
    Configured: "已配置",
    "Not configured": "未配置",
    "Official guide": "官方指南",
    "Open OpenAI API Keys": "打开 OpenAI API 密钥",
    "Open Gemini API Keys": "打开 Gemini API 密钥",
    "Open the OpenAI API Keys page and sign in.": "打开 OpenAI API 密钥页面并登录。",
    "Select Create new secret key and copy it when it is shown.": "选择创建新的密钥，并在显示时复制。",
    "Paste it into OpenAI API key above, then save settings.": "将其粘贴到上方的 OpenAI API 密钥字段，然后保存设置。",
    "Open the Gemini API Keys page and sign in with your Google account.": "打开 Gemini API 密钥页面并使用 Google 账号登录。",
    "Select Create API key, choose a project, and copy the generated key.": "选择创建 API 密钥，选择一个项目，然后复制生成的密钥。",
    "Paste it into Gemini API key above, then save settings.": "将其粘贴到上方的 Gemini API 密钥字段，然后保存设置。",
    "Expand sidebar": "展开侧边栏",
    "Collapse sidebar": "收起侧边栏",
    "Primary navigation": "主导航",
    Available: "可用",
    "Keyword projects, screenshots, reports, browser sessions, and keys stay on this machine.": "关键词项目、截图、报告、浏览器会话和密钥均保留在本机。",
    "Developer profile": "开发者资料",
    Developer: "开发者",
    "Open developer profile": "打开开发者资料",
    Ready: "就绪",
    Deleting: "正在删除",
    Mobile: "移动端",
    Desktop: "桌面端",
    Actions: "操作",
    Select: "选择",
    Source: "来源",
    Reason: "原因",
    "Product Title": "产品标题",
    "Product Type": "产品类型",
    "Monthly Sold": "月销量",
    "Store Name": "店铺名称",
    "Store Type": "店铺类型",
    Price: "价格",
    "Total Sold": "总销量",
    products: "件产品",
    stores: "家店铺",
    complete: "完成",
    "No category": "未分类",
    "All shop types": "全部店铺类型",
    "All prices": "全部价格",
    From: "起价",
    "Up to": "最高",
    "No minimum": "无最低价",
    "No maximum": "无最高价",
    "Market Scope": "市场范围",
    "Applied filters & market coverage": "已应用筛选与市场覆盖",
    "Collected marketplace stores": "已采集的市场店铺",
    "Shop type": "店铺类型",
    "Price range": "价格范围",
    "Product evidence": "产品证据",
    "Shop Type Filters": "店铺类型筛选",
    "Delete project": "删除项目",
    "Delete keyword project?": "删除关键词项目？",
    "This permanently removes the project, evidence, reports, and local files. Type": "此操作将永久删除项目、证据、报告和本地文件。请输入",
    "to confirm.": "以确认。",
    "Project name confirmation": "项目名称确认",
    "Card view": "卡片视图",
    "List view": "列表视图",
    "Marketplace product evidence": "市场产品证据",
    "Store pending": "店铺待确认",
    "Preview product image": "预览产品图片",
    "Product image preview": "产品图片预览",
    "Rating evidence": "评分证据",
    "Store rating evidence preview": "店铺评分证据预览",
    "File preview": "文件预览",
    "Show in folder": "在文件夹中显示",
    "DOCX document preview": "DOCX 文档预览",
    Slide: "幻灯片",
    "Remove product": "移除产品",
    "Zoom in": "放大",
    "Zoom out": "缩小",
    "Use Ctrl/Command + wheel to zoom, then drag to pan.": "使用 Ctrl/Command 加滚轮缩放，然后拖动平移。",
    "Monthly sold only applies to Top Sales result snapshots. Total sold is collected from PDP evidence when visible.": "月销量仅适用于热销结果快照。总销量会在商品详情页证据可见时采集。",
    "Rating is the star value; Reviews is the rating/review count. Price ranges are stored as estimated average price.": "评分为星级数值；评论为评分或评论数量。价格范围以估算平均价保存。",
    "Project Inspector": "项目检查器",
    "Loading project evidence...": "正在加载项目证据...",
    "No keyword projects match the current search and category.": "没有符合当前搜索和分类的关键词项目。",
    "Capture Relevance and Top Sales first to generate dynamic product detail steps.": "请先采集相关性和热销结果，以生成动态商品详情步骤。",
    "No collected data yet for this section.": "此章节尚无采集数据。",
    "Preparing preview...": "正在准备预览...",
    "The PDF preview could not be displayed.": "无法显示 PDF 预览。",
    "No rendered product rows extracted yet.": "尚未提取到可显示的产品行。",
    "Product info table is empty. Capture Relevance and Top Sales pages first.": "产品信息表为空。请先采集相关性和热销页面。",
    "No product image URLs captured yet.": "尚未采集产品图片 URL。",
    "No product video URLs captured yet.": "尚未采集产品视频 URL。",
    "No review text collected yet. Capture the review section with 3 positive and 2 negative examples visible.": "尚未采集评论文本。请采集包含 3 条正面和 2 条负面示例的评论区域。",
    "Store details have not been collected.": "尚未采集店铺详情。",
    "No store categories collected.": "尚未采集店铺分类。",
    Activity: "活动",
    "Platform Browser": "平台浏览器",
    "TikTok Analysis Session": "TikTok 分析会话",
    "Mobile Collection Steps": "移动端采集步骤",
    "Android Emulator Workspace": "Android 模拟器工作区",
    "Bulk Report Generation": "批量报告生成",
    "Select by category": "按分类选择",
    "No bulk report ZIP generated yet.": "尚未生成批量报告 ZIP。",
    "2. Choose Report Content": "2. 选择报告内容",
    "Key Product Table": "关键产品表",
    Email: "电子邮箱",
    Password: "密码",
    "License key": "许可证密钥",
    Completed: "已完成",
    Incomplete: "未完成",
    "Activate Research Product Market": "激活产品市场研究",
    "Enter the email, password, and signed license issued for this device.": "请输入此设备获发的电子邮箱、密码和签名许可证。",
    "Activate and sign in": "激活并登录",
    "Verifying license": "正在验证许可证",
    "Machine ID:": "机器 ID：",
    "Marketplace research and evidence workspace": "市场研究与证据工作区",
    "Made by": "制作人",
    "Launch Android, install or open TikTok, log in with Gmail if needed, then enter TikTok Shop manually. Closing the emulator keeps the AVD data partition, installed apps, and login state.": "启动 Android，安装或打开 TikTok，必要时使用 Gmail 登录，然后手动进入 TikTok Shop。关闭模拟器会保留 AVD 数据、已安装应用和登录状态。",
    Step: "步骤",
    Refresh: "刷新",
    "Emulator launch is persistent by design. The app does not wipe Android, uninstall TikTok, clear app data, or reset Google login when the emulator is closed.": "模拟器按设计保持持久状态。关闭模拟器时不会清除 Android、卸载 TikTok、删除应用数据或重置 Google 登录。",
    "TikTok is not responding": "TikTok 无响应",
    "Android reported an ANR in TikTok. Recovery force-stops and reopens TikTok only; it keeps the emulator profile, installed app, and account data intact.": "Android 报告 TikTok 无响应。恢复操作只会强制停止并重新打开 TikTok，同时保留模拟器配置、已安装应用和账户数据。",
    "Active Step": "当前步骤",
    "Manual action required": "需要手动操作",
    "Shopee is showing login, verification, captcha, or a protected page. Complete it manually, then capture evidence after the target page is visible.": "Shopee 正在显示登录、验证、验证码或受保护页面。请手动完成，然后在目标页面可见后采集证据。",
    "Preview: Key Product Table": "预览：关键产品表",
    "selected from": "选自",
    "extracted rows.": "条已提取记录。",
    Type: "类型",
    Star: "星级",
    "Comment - timepost": "评论 - 发布时间",
    "Description preview": "描述预览",
    "Live store result preview": "店铺结果实时预览",
    "Step Actions": "步骤操作",
    Updating: "正在更新",
    Browser: "浏览器",
    "Every distinct store from Product Qualified is listed once. Review the list, add another Shopee store when needed, then collect each store page independently.": "关键产品中的每个不同店铺只列出一次。请审核列表，必要时添加其他 Shopee 店铺，然后分别采集每个店铺页面。",
    "Key Store Page": "关键店铺页面",
    "Shop ID": "店铺 ID",
    "Add Store Page": "添加店铺页面",
    "Add store page": "添加店铺页面",
    "Store name": "店铺名称",
    "Shopee store URL": "Shopee 店铺 URL",
    Add: "添加",
    "Save Store List": "保存店铺列表",
    "Manually added": "手动添加",
    "Add at least one Key Store Page to continue.": "请至少添加一个关键店铺页面后继续。",
    "Guided Collection": "引导式采集",
    "Recommended:": "建议：",
    "Open Target": "打开目标",
    "Open the matching product page before collecting Product Detail data.": "采集产品详情数据前，请打开匹配的产品页面。",
    "Open TikTok": "打开 TikTok",
    "Attach Shot": "附加截图",
    "Review Screenshot": "查看截图",
    "Save Full": "保存完整截图",
    Redo: "重做",
    "Scroll to move through the preview. Use zoom buttons or Ctrl/Command + wheel to zoom, then drag to pan. Use Select Area before dragging a crop box.": "滚动以浏览预览。使用缩放按钮或 Ctrl/Command 加滚轮缩放，然后拖动平移。拖动裁剪框前请先选择区域。",
    "Product Qualified starts with Top Sales evidence, then uses Relevance evidence to enrich and rank commercially valid products.": "关键产品先使用热销证据，再使用相关性证据补充并排序具有商业价值的产品。",
    "GIMMICK, NOT FOR SALE, FREE GIFT, irrelevant, and duplicate rows are excluded. Review up to 20 products before approval.": "将排除噱头、非卖品、赠品、不相关和重复记录。批准前最多审核 20 个产品。",
    Showing: "显示",
    from: "来自",
    selected: "已选择",
    "Exclude selected": "排除所选项",
    "Add another qualified product": "添加其他关键产品",
    "Select product": "选择产品",
    "Add Product": "添加产品",
    "Add 5 more product": "再添加 5 个产品",
    "Available products": "可用产品",
    "Add selected": "添加所选项",
    "Maximum 20 qualified products reached.": "已达到 20 个关键产品上限。",
    "Store Name, Total Sold, review detail, slides, description, and shop homepage are enriched during Product Detail Qualified collection.": "店铺名称、总销量、评论详情、幻灯片、描述和店铺首页会在关键产品详情采集中补充。",
    Next: "下一步",
    "No promotion signal captured yet.": "尚未采集促销信号。",
    "Slides and Images": "幻灯片与图片",
    Videos: "视频",
    "Media in User": "用户媒体",
    Variants: "规格选项",
    "No variants detected.": "未检测到规格选项。",
    Specifications: "规格参数",
    "No specifications detected.": "未检测到规格参数。",
    Video: "视频",
    "Star Rated": "星级评分",
    "Comment - Include timestamp": "评论 - 包含时间",
    "Choose a category": "选择分类",
    "Select multiple projects from": "从以下分类选择多个项目",
    "files packaged in": "个文件已打包至",
    "Open ZIP": "打开 ZIP",
    "Bulk Report History": "批量报告历史",
    projects: "个项目",
    files: "个文件",
    "Report generated at": "报告生成于",
    "Enable the sections needed in the final report. Drag section groups to reorder them.": "启用最终报告所需章节。拖动章节组可调整顺序。",
    of: "/",
    enabled: "已启用",
    "Drag this parent section to change report order.": "拖动此父章节可更改报告顺序。",
    "Report Preview": "报告预览",
    "Preview report": "预览报告",
    "Open DOCX": "打开 DOCX",
    "Open HTML": "打开 HTML",
    "Preview zoom controls": "预览缩放控件",
    "Rendering DOCX preview...": "正在渲染 DOCX 预览...",
    "DOCX pages": "DOCX 页面",
    "Collapse report navigation": "收起报告导航",
    "Expand report navigation": "展开报告导航",
    "Report preview": "报告预览",
    "Report headings": "报告标题",
    Contents: "目录",
    "Close report preview": "关闭报告预览",
    "Launch Emulator": "启动模拟器",
    "Select APK": "选择 APK",
    "Install TikTok": "安装 TikTok",
    "Open TikTok App": "打开 TikTok 应用"
  }
};

export function isAppLanguage(value: unknown): value is AppLanguage {
  return value === "en-US" || value === "id-ID" || value === "zh-CN";
}

export function translate(language: AppLanguage, source: string): string {
  if (language === "en-US") {
    return source;
  }
  return TRANSLATIONS[language][source] ?? source;
}

export function languageOption(language: AppLanguage): AppLanguageOption {
  return APP_LANGUAGES.find((option) => option.id === language) ?? APP_LANGUAGES[0];
}
